"""OSS baseline schema.

Single squashed baseline for the open-source lemma-backend: the full
connector schema (tables all indexes incl. the
functional GIN/tsvector search indexes, and every constraint) as one clean
starting point. The pre-release iteration history lives only in lemma-cloud's
migration chain.

Revision ID: 0001_oss_baseline
"""

from alembic import op

revision = "0001_oss_baseline"
down_revision = None
branch_labels = None
depends_on = None

# Generated from the squashed schema (pg_dump of the full chain, billing
# tables dropped). Statements are ordered: enum -> tables -> constraints ->
# indexes, and executed one-by-one (the alembic engine is asyncpg, which
# does not accept multi-statement execute()).
_STATEMENTS = [
    'CREATE TABLE public.accounts (\n    user_id uuid NOT NULL,\n    connector_id character varying(255) NOT NULL,\n    provider_account_id character varying(255),\n    email character varying(255),\n    credentials jsonb,\n    preferences jsonb,\n    allowed_scopes text[],\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    organization_id uuid NOT NULL,\n    auth_config_id uuid NOT NULL,\n    status character varying(50) NOT NULL\n)',
    'CREATE TABLE public.agent_approval_decisions (\n    id uuid NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    conversation_id uuid NOT NULL,\n    agent_run_id uuid,\n    approval_id character varying(255) NOT NULL,\n    tool_name character varying(255),\n    decision character varying(32) NOT NULL,\n    response jsonb,\n    resolved_by_user_id uuid\n)',
    'CREATE TABLE public.agent_conversations (\n    user_id uuid NOT NULL,\n    pod_id uuid NOT NULL,\n    organization_id uuid,\n    agent_id uuid,\n    title character varying(255),\n    parent_id uuid,\n    conversation_metadata jsonb,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    instructions text,\n    conversation_type character varying(32) NOT NULL,\n    status character varying(32),\n    output_data jsonb,\n    agent_runtime jsonb\n)',
    'CREATE TABLE public.agent_feedback (\n    user_id uuid NOT NULL,\n    agent_id uuid,\n    category character varying(32) NOT NULL,\n    subject character varying(255) NOT NULL,\n    issue_encountered text NOT NULL,\n    expected_behavior text NOT NULL,\n    actual_behavior text NOT NULL,\n    suggested_next_steps text,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL\n)',
    'CREATE TABLE public.agent_messages (\n    conversation_id uuid NOT NULL,\n    agent_run_id uuid,\n    sequence bigint NOT NULL,\n    role character varying(32) NOT NULL,\n    tool_call_id character varying(255),\n    tool_name character varying(255),\n    message_metadata jsonb,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    kind character varying(32) NOT NULL,\n    text text,\n    tool_args jsonb,\n    tool_result jsonb\n)',
    'CREATE TABLE public.agent_runs (\n    conversation_id uuid NOT NULL,\n    agent_id uuid,\n    parent_run_id uuid,\n    status character varying(32) NOT NULL,\n    started_at timestamp with time zone NOT NULL,\n    finished_at timestamp with time zone,\n    error text,\n    output_data jsonb,\n    run_metadata jsonb,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    agent_runtime jsonb NOT NULL\n)',
    "CREATE TABLE public.agent_runtime_daemons (\n    id uuid NOT NULL,\n    user_id uuid NOT NULL,\n    device_key character varying(255) NOT NULL,\n    display_name character varying(255) NOT NULL,\n    status character varying(32) DEFAULT 'OFFLINE'::character varying NOT NULL,\n    device_info jsonb DEFAULT '{}'::jsonb NOT NULL,\n    harness_catalog jsonb DEFAULT '{}'::jsonb NOT NULL,\n    last_seen_at timestamp with time zone,\n    connected_at timestamp with time zone,\n    disconnected_at timestamp with time zone,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL\n)",
    "CREATE TABLE public.agent_runtime_profiles (\n    id uuid NOT NULL,\n    organization_id uuid NOT NULL,\n    scope character varying(32) NOT NULL,\n    kind character varying(32) NOT NULL,\n    protocol character varying(32) NOT NULL,\n    name character varying(255) NOT NULL,\n    description text,\n    default_model_name character varying(255),\n    model_catalog jsonb DEFAULT '[]'::jsonb NOT NULL,\n    config jsonb DEFAULT '{}'::jsonb NOT NULL,\n    credentials jsonb,\n    status character varying(32) DEFAULT 'ACTIVE'::character varying NOT NULL,\n    profile_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    user_id uuid,\n    daemon_id uuid\n)",
    "CREATE TABLE public.agent_surface_conversation_links (\n    surface_id uuid NOT NULL,\n    conversation_id uuid NOT NULL,\n    platform character varying(50) NOT NULL,\n    external_channel_id character varying(255),\n    external_thread_id character varying(255) NOT NULL,\n    external_user_id character varying(255),\n    last_event jsonb NOT NULL,\n    last_message_id character varying(255),\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    routed_agent_id uuid,\n    conversation_kind character varying(50) DEFAULT 'DM'::character varying NOT NULL,\n    route_key character varying(255)\n)",
    'CREATE TABLE public.agent_surface_external_users (\n    platform character varying(50) NOT NULL,\n    tenant_id character varying(255),\n    external_user_id character varying(255) NOT NULL,\n    email character varying(255),\n    phone character varying(64),\n    display_name character varying(255),\n    raw_profile jsonb NOT NULL,\n    resolved_user_id uuid,\n    last_seen_at timestamp with time zone,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL\n)',
    "CREATE TABLE public.agent_surfaces (\n    pod_id uuid NOT NULL,\n    agent_id uuid,\n    surface_type character varying(50) NOT NULL,\n    config jsonb NOT NULL,\n    status character varying(50) DEFAULT 'ACTIVE'::character varying NOT NULL,\n    schedule_id uuid,\n    surface_identity_email character varying(255),\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    mode character varying(50) NOT NULL,\n    account_id uuid,\n    external_workspace_id character varying(255),\n    external_tenant_id character varying(255),\n    external_channel_id character varying(255),\n    surface_identity_id character varying(255),\n    event_mode character varying(50) DEFAULT 'WEBHOOK'::character varying NOT NULL,\n    webhook_secret character varying(255),\n    credential_mode character varying(50) DEFAULT 'SYSTEM'::character varying NOT NULL,\n    surface_identity_username character varying(255)\n)",
    'CREATE TABLE public.agents (\n    pod_id uuid NOT NULL,\n    user_id uuid NOT NULL,\n    name character varying(255) NOT NULL,\n    description text,\n    icon_url text,\n    visibility character varying(15) NOT NULL,\n    instruction text NOT NULL,\n    toolsets jsonb NOT NULL,\n    input_schema jsonb,\n    output_schema jsonb,\n    agent_metadata jsonb,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    agent_runtime jsonb\n)',
    'CREATE TABLE public.connector_operations (\n    connector_id character varying(255) NOT NULL,\n    name character varying(255) NOT NULL,\n    provider_operation_name character varying(255),\n    display_name character varying(255),\n    description text,\n    input_schema jsonb,\n    output_schema jsonb,\n    id character varying NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    search_document text,\n    provider character varying(50) NOT NULL\n)',
    'CREATE TABLE public.connector_triggers (\n    connector_id character varying(255) NOT NULL,\n    event_type character varying(255) NOT NULL,\n    description text,\n    config_schema jsonb,\n    payload_schema jsonb,\n    payload_example jsonb,\n    id character varying NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    provider character varying(50) NOT NULL\n)',
    'CREATE TABLE public.connectors (\n    title character varying(255),\n    description text,\n    icon character varying(500),\n    agent_instruction text,\n    is_active boolean NOT NULL,\n    id character varying NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    provider_capabilities jsonb NOT NULL\n)',
    'CREATE TABLE public.assistants (\n    pod_id uuid NOT NULL,\n    user_id uuid NOT NULL,\n    visibility character varying(15) NOT NULL,\n    name character varying(255) NOT NULL,\n    description text,\n    icon_url text,\n    instruction text NOT NULL,\n    tool_sets character varying[] NOT NULL,\n    accessible_tables character varying[] NOT NULL,\n    accessible_table_permissions jsonb NOT NULL,\n    accessible_folders character varying[] NOT NULL,\n    accessible_connectors jsonb NOT NULL,\n    function_names character varying[] NOT NULL,\n    agent_names character varying[] NOT NULL,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL\n)',
    'CREATE TABLE public.auth_configs (\n    organization_id uuid NOT NULL,\n    connector_id character varying(255) NOT NULL,\n    name text NOT NULL,\n    provider character varying(50) NOT NULL,\n    config_source character varying(50) NOT NULL,\n    status character varying(50) NOT NULL,\n    provider_config jsonb,\n    metadata jsonb,\n    created_by_user_id uuid,\n    updated_by_user_id uuid,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL\n)',
    'CREATE TABLE public.auth_permissions (\n    id character varying NOT NULL,\n    scope character varying(30) NOT NULL,\n    resource_type character varying(120),\n    description text NOT NULL,\n    system_only boolean DEFAULT false NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL\n)',
    'CREATE TABLE public.connect_requests (\n    user_id uuid NOT NULL,\n    connector_id character varying(255) NOT NULL,\n    authorization_url text,\n    status character varying(50) NOT NULL,\n    attributes jsonb,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    organization_id uuid NOT NULL,\n    auth_config_id uuid NOT NULL\n)',
    'CREATE TABLE public.conversation_messages (\n    conversation_id uuid NOT NULL,\n    role character varying(50) NOT NULL,\n    content jsonb NOT NULL,\n    user_id uuid,\n    external_user_id character varying(255),\n    external_message_id character varying(255),\n    message_metadata jsonb,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL\n)',
    'CREATE TABLE public.conversations (\n    pod_id uuid,\n    organization_id uuid,\n    assistant_id uuid,\n    surface_installation_id uuid,\n    user_id uuid NOT NULL,\n    title character varying(255),\n    conversation_type character varying(32) NOT NULL,\n    surface_type character varying(50),\n    external_thread_id character varying(255),\n    external_channel_id character varying(255),\n    external_user_id character varying(255),\n    model character varying(64),\n    status character varying(32) NOT NULL,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL\n)',
    'CREATE TABLE public.datastore_files (\n    pod_id uuid NOT NULL,\n    owner_user_id uuid NOT NULL,\n    kind character varying(32) NOT NULL,\n    path character varying(1024) NOT NULL,\n    name character varying(255) NOT NULL,\n    description text,\n    mime_type character varying(255),\n    size_bytes bigint NOT NULL,\n    search_enabled boolean NOT NULL,\n    status character varying(50) NOT NULL,\n    file_metadata jsonb,\n    indexed_at timestamp with time zone,\n    last_processing_error text,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    visibility character varying(30) NOT NULL,\n    processing_attempts integer DEFAULT 0 NOT NULL\n)',
    'CREATE TABLE public.datastore_tables (\n    pod_id uuid NOT NULL,\n    user_id uuid,\n    table_name character varying(255) NOT NULL,\n    primary_key_column character varying(255) NOT NULL,\n    columns jsonb NOT NULL,\n    config jsonb,\n    enable_rls boolean NOT NULL,\n    visibility character varying(15) NOT NULL,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL\n)',
    'CREATE TABLE public.app_releases (\n    app_id uuid NOT NULL,\n    version character varying NOT NULL,\n    dist_root_path character varying NOT NULL,\n    dist_archive_path character varying,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL\n)',
    'CREATE TABLE public.apps (\n    pod_id uuid NOT NULL,\n    user_id uuid NOT NULL,\n    name character varying NOT NULL,\n    public_slug character varying NOT NULL,\n    description text,\n    source_archive_path character varying,\n    current_release_id uuid,\n    status character varying NOT NULL,\n    visibility character varying(15) NOT NULL,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL\n)',
    'CREATE TABLE public.function_runs (\n    function_id uuid NOT NULL,\n    user_id uuid NOT NULL,\n    input_data jsonb,\n    output_data jsonb,\n    status character varying NOT NULL,\n    user_email text,\n    job_id character varying,\n    workspace_session_id character varying,\n    workspace_process_id character varying,\n    error text,\n    logs text,\n    started_at timestamp without time zone,\n    completed_at timestamp without time zone,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL\n)',
    'CREATE TABLE public.functions (\n    pod_id uuid NOT NULL,\n    user_id uuid NOT NULL,\n    name character varying NOT NULL,\n    description text,\n    icon_url text,\n    input_schema jsonb NOT NULL,\n    output_schema jsonb NOT NULL,\n    config_schema jsonb,\n    code_path character varying,\n    config jsonb,\n    type character varying NOT NULL,\n    status character varying NOT NULL,\n    visibility character varying(15) NOT NULL,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    code_hash character varying\n)',
    'CREATE TABLE public.organization_invitations (\n    email character varying(255) NOT NULL,\n    organization_id uuid NOT NULL,\n    role character varying(50) NOT NULL,\n    pod_id uuid,\n    pod_role character varying(50),\n    status character varying(50) NOT NULL,\n    expires_at timestamp with time zone NOT NULL,\n    accepted_at timestamp with time zone,\n    revoked_at timestamp with time zone,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    redirect_uri character varying(2048)\n)',
    'CREATE TABLE public.organization_members (\n    user_id uuid NOT NULL,\n    organization_id uuid NOT NULL,\n    role character varying(50) NOT NULL,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL\n)',
    'CREATE TABLE public.organizations (\n    name character varying(255) NOT NULL,\n    slug character varying(255) NOT NULL,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    email_domain character varying(255),\n    allow_auto_join boolean NOT NULL\n)',
    'CREATE TABLE public.pod_join_requests (\n    pod_id uuid NOT NULL,\n    organization_id uuid NOT NULL,\n    user_id uuid NOT NULL,\n    status character varying(50) NOT NULL,\n    requested_at timestamp with time zone NOT NULL,\n    approved_at timestamp with time zone,\n    approved_by_user_id uuid,\n    org_role character varying(50),\n    pod_role character varying(50),\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL\n)',
    'CREATE TABLE public.pod_members (\n    pod_id uuid NOT NULL,\n    organization_member_id uuid NOT NULL,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL\n)',
    "CREATE TABLE public.pods (\n    user_id uuid NOT NULL,\n    organization_id uuid NOT NULL,\n    name character varying(255) NOT NULL,\n    description text,\n    icon_url text,\n    is_deleted boolean NOT NULL,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    config jsonb DEFAULT '{}'::jsonb NOT NULL\n)",
    'CREATE TABLE public.resource_permission_grants (\n    pod_id uuid NOT NULL,\n    resource_type character varying(120) NOT NULL,\n    resource_id uuid NOT NULL,\n    grantee_type character varying(40) NOT NULL,\n    grantee_id uuid NOT NULL,\n    permission_id character varying NOT NULL,\n    created_by_user_id uuid,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL\n)',
    'CREATE TABLE public.role_assignments (\n    role_id uuid NOT NULL,\n    principal_type character varying(40) NOT NULL,\n    principal_id uuid NOT NULL,\n    assigned_by_user_id uuid,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL\n)',
    'CREATE TABLE public.role_permissions (\n    role_id uuid NOT NULL,\n    permission_id character varying NOT NULL,\n    granted_by_user_id uuid,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL\n)',
    'CREATE TABLE public.roles (\n    organization_id uuid NOT NULL,\n    pod_id uuid,\n    name character varying(120) NOT NULL,\n    description text,\n    is_system boolean DEFAULT false NOT NULL,\n    created_by_user_id uuid,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL\n)',
    'CREATE TABLE public.schedules (\n    user_id uuid NOT NULL,\n    pod_id uuid,\n    schedule_type character varying(50) NOT NULL,\n    account_id uuid,\n    connector_trigger_id character varying,\n    config jsonb NOT NULL,\n    filter_instruction text,\n    filter_output_schema jsonb,\n    is_active boolean NOT NULL,\n    is_internal boolean NOT NULL,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    workflow_id uuid,\n    agent_id uuid,\n    visibility character varying(30) NOT NULL,\n    name character varying(255),\n    last_fired_at timestamp with time zone,\n    last_run_id character varying(255),\n    last_fire_status character varying(20),\n    last_error text\n)',
    'CREATE TABLE public.usage_limit_counters (\n    organization_id uuid,\n    user_id uuid,\n    window_kind character varying(32) NOT NULL,\n    window_start timestamp with time zone NOT NULL,\n    window_end timestamp with time zone NOT NULL,\n    used_usd double precision NOT NULL,\n    reserved_usd double precision NOT NULL,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL\n)',
    'CREATE TABLE public.usage_records (\n    organization_id uuid,\n    pod_id uuid,\n    user_id uuid NOT NULL,\n    model_name character varying(160) NOT NULL,\n    input_tokens integer NOT NULL,\n    output_tokens integer NOT NULL,\n    metadata jsonb,\n    occurred_at timestamp with time zone NOT NULL,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    agent_id uuid,\n    conversation_id uuid,\n    agent_run_id uuid,\n    usage_kind character varying(40) NOT NULL,\n    units double precision NOT NULL,\n    status character varying(32),\n    parent_agent_run_id uuid,\n    source_type character varying(60) NOT NULL,\n    source_id character varying(120),\n    profile_id character varying(120) NOT NULL,\n    profile_scope character varying(32) NOT NULL,\n    cost_usd double precision\n)',
    'CREATE TABLE public.users (\n    email character varying(255) NOT NULL,\n    is_verified boolean NOT NULL,\n    is_active boolean NOT NULL,\n    is_superuser boolean NOT NULL,\n    is_deleted boolean NOT NULL,\n    first_name character varying(100),\n    last_name character varying(100),\n    mobile_number character varying(32),\n    country character varying(100),\n    timezone character varying(50),\n    date_of_birth date,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    telegram_username character varying(255)\n)',
    "CREATE TABLE public.workflow_flow_runs (\n    flow_id uuid NOT NULL,\n    pod_id uuid NOT NULL,\n    user_id uuid NOT NULL,\n    start_type character varying NOT NULL,\n    status character varying NOT NULL,\n    current_node_id character varying,\n    execution_context jsonb NOT NULL,\n    execution_stack jsonb NOT NULL,\n    step_history jsonb NOT NULL,\n    started_at timestamp without time zone,\n    completed_at timestamp without time zone,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    schedule_event_id character varying,\n    start_payload jsonb DEFAULT '{}'::jsonb NOT NULL,\n    error text,\n    failed_node_id character varying\n)",
    'CREATE TABLE public.workflow_flows (\n    pod_id uuid NOT NULL,\n    user_id uuid,\n    name character varying NOT NULL,\n    description character varying,\n    icon_url character varying,\n    nodes jsonb NOT NULL,\n    edges jsonb NOT NULL,\n    start jsonb,\n    mode character varying NOT NULL,\n    is_active boolean NOT NULL,\n    visibility character varying(15) NOT NULL,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    entry_node_id character varying\n)',
    'CREATE TABLE public.workflow_run_waits (\n    run_id uuid NOT NULL,\n    flow_id uuid NOT NULL,\n    pod_id uuid NOT NULL,\n    node_id character varying NOT NULL,\n    wait_type character varying(30) NOT NULL,\n    status character varying(30) NOT NULL,\n    assigned_pod_member_id uuid,\n    external_ref character varying,\n    payload jsonb NOT NULL,\n    completed_at timestamp with time zone,\n    id uuid NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL\n)',
    'ALTER TABLE ONLY public.accounts\n    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.agent_approval_decisions\n    ADD CONSTRAINT agent_approval_decisions_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.agent_conversations\n    ADD CONSTRAINT agent_conversations_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.agent_feedback\n    ADD CONSTRAINT agent_feedback_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.agent_messages\n    ADD CONSTRAINT agent_messages_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.agent_runs\n    ADD CONSTRAINT agent_runs_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.agent_runtime_daemons\n    ADD CONSTRAINT agent_runtime_daemons_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.agent_runtime_profiles\n    ADD CONSTRAINT agent_runtime_profiles_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.agent_surface_conversation_links\n    ADD CONSTRAINT agent_surface_conversation_links_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.agents\n    ADD CONSTRAINT agents_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.connector_operations\n    ADD CONSTRAINT connector_operations_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.connector_triggers\n    ADD CONSTRAINT connector_triggers_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.connectors\n    ADD CONSTRAINT connectors_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.agent_surface_external_users\n    ADD CONSTRAINT assistant_surface_external_users_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.agent_surfaces\n    ADD CONSTRAINT assistant_surfaces_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.assistants\n    ADD CONSTRAINT assistants_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.auth_configs\n    ADD CONSTRAINT auth_configs_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.auth_permissions\n    ADD CONSTRAINT auth_permissions_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.connect_requests\n    ADD CONSTRAINT connect_requests_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.conversation_messages\n    ADD CONSTRAINT conversation_messages_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.conversations\n    ADD CONSTRAINT conversations_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.datastore_files\n    ADD CONSTRAINT datastore_files_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.datastore_tables\n    ADD CONSTRAINT datastore_tables_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.app_releases\n    ADD CONSTRAINT app_releases_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.apps\n    ADD CONSTRAINT apps_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.function_runs\n    ADD CONSTRAINT function_runs_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.functions\n    ADD CONSTRAINT functions_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.organization_invitations\n    ADD CONSTRAINT organization_invitations_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.organization_members\n    ADD CONSTRAINT organization_members_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.organizations\n    ADD CONSTRAINT organizations_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.pod_join_requests\n    ADD CONSTRAINT pod_join_requests_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.pod_members\n    ADD CONSTRAINT pod_members_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.pods\n    ADD CONSTRAINT pods_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.resource_permission_grants\n    ADD CONSTRAINT resource_permission_grants_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.role_assignments\n    ADD CONSTRAINT role_assignments_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.role_permissions\n    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.roles\n    ADD CONSTRAINT roles_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.schedules\n    ADD CONSTRAINT triggers_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.agent_approval_decisions\n    ADD CONSTRAINT uq_agent_approval_decision UNIQUE (conversation_id, approval_id)',
    'ALTER TABLE ONLY public.agent_messages\n    ADD CONSTRAINT uq_agent_message_sequence UNIQUE (conversation_id, sequence)',
    'ALTER TABLE ONLY public.agents\n    ADD CONSTRAINT uq_agent_pod_name UNIQUE (pod_id, name)',
    'ALTER TABLE ONLY public.agent_runtime_daemons\n    ADD CONSTRAINT uq_agent_runtime_daemon_user_device UNIQUE (user_id, device_key)',
    'ALTER TABLE ONLY public.assistants\n    ADD CONSTRAINT uq_assistant_pod_name UNIQUE (pod_id, name)',
    'ALTER TABLE ONLY public.apps\n    ADD CONSTRAINT uq_app_pod_name UNIQUE (pod_id, name)',
    'ALTER TABLE ONLY public.apps\n    ADD CONSTRAINT uq_app_public_slug UNIQUE (public_slug)',
    'ALTER TABLE ONLY public.app_releases\n    ADD CONSTRAINT uq_app_release_version UNIQUE (app_id, version)',
    'ALTER TABLE ONLY public.functions\n    ADD CONSTRAINT uq_function_pod_name UNIQUE (pod_id, name)',
    'ALTER TABLE ONLY public.resource_permission_grants\n    ADD CONSTRAINT uq_resource_permission_grants_scope UNIQUE (pod_id, resource_type, resource_id, grantee_type, grantee_id, permission_id)',
    'ALTER TABLE ONLY public.role_assignments\n    ADD CONSTRAINT uq_role_assignments_role_principal UNIQUE (role_id, principal_type, principal_id)',
    'ALTER TABLE ONLY public.role_permissions\n    ADD CONSTRAINT uq_role_permissions_role_permission UNIQUE (role_id, permission_id)',
    'ALTER TABLE ONLY public.workflow_flows\n    ADD CONSTRAINT uq_workflow_flow_pod_name UNIQUE (pod_id, name)',
    'ALTER TABLE ONLY public.workflow_flow_runs\n    ADD CONSTRAINT uq_workflow_run_flow_user_schedule_event UNIQUE (flow_id, user_id, schedule_event_id)',
    'ALTER TABLE ONLY public.usage_limit_counters\n    ADD CONSTRAINT usage_limit_counters_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.usage_records\n    ADD CONSTRAINT usage_records_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.users\n    ADD CONSTRAINT users_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.workflow_flow_runs\n    ADD CONSTRAINT workflow_flow_runs_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.workflow_flows\n    ADD CONSTRAINT workflow_flows_pkey PRIMARY KEY (id)',
    'ALTER TABLE ONLY public.workflow_run_waits\n    ADD CONSTRAINT workflow_run_waits_pkey PRIMARY KEY (id)',
    'CREATE INDEX ix_accounts_id ON public.accounts USING btree (id)',
    'CREATE INDEX ix_accounts_provider_account_id ON public.accounts USING btree (provider_account_id)',
    'CREATE INDEX ix_agent_approval_decision_conversation ON public.agent_approval_decisions USING btree (conversation_id, approval_id)',
    'CREATE INDEX ix_agent_approval_decisions_conversation_id ON public.agent_approval_decisions USING btree (conversation_id)',
    'CREATE INDEX ix_agent_conv_metadata ON public.agent_conversations USING gin (conversation_metadata)',
    'CREATE INDEX ix_agent_conv_parent ON public.agent_conversations USING btree (parent_id)',
    'CREATE INDEX ix_agent_conv_pod_agent_roots ON public.agent_conversations USING btree (pod_id, agent_id, user_id, parent_id, id)',
    'CREATE INDEX ix_agent_conv_pod_assistant_roots ON public.agent_conversations USING btree (user_id, agent_id, pod_id, parent_id, id)',
    'CREATE INDEX ix_agent_conversations_agent_id ON public.agent_conversations USING btree (agent_id)',
    'CREATE INDEX ix_agent_conversations_conversation_type ON public.agent_conversations USING btree (conversation_type)',
    'CREATE INDEX ix_agent_conversations_id ON public.agent_conversations USING btree (id)',
    'CREATE INDEX ix_agent_conversations_organization_id ON public.agent_conversations USING btree (organization_id)',
    'CREATE INDEX ix_agent_conversations_parent_id ON public.agent_conversations USING btree (parent_id)',
    'CREATE INDEX ix_agent_conversations_pod_id ON public.agent_conversations USING btree (pod_id)',
    'CREATE INDEX ix_agent_conversations_status ON public.agent_conversations USING btree (status)',
    'CREATE INDEX ix_agent_conversations_user_id ON public.agent_conversations USING btree (user_id)',
    'CREATE INDEX ix_agent_feedback_agent_created ON public.agent_feedback USING btree (agent_id, created_at)',
    'CREATE INDEX ix_agent_feedback_agent_id ON public.agent_feedback USING btree (agent_id)',
    'CREATE INDEX ix_agent_feedback_category ON public.agent_feedback USING btree (category)',
    'CREATE INDEX ix_agent_feedback_id ON public.agent_feedback USING btree (id)',
    'CREATE INDEX ix_agent_feedback_user_created ON public.agent_feedback USING btree (user_id, created_at)',
    'CREATE INDEX ix_agent_feedback_user_id ON public.agent_feedback USING btree (user_id)',
    'CREATE INDEX ix_agent_message_conversation_sequence ON public.agent_messages USING btree (conversation_id, sequence)',
    'CREATE INDEX ix_agent_message_run_sequence ON public.agent_messages USING btree (agent_run_id, sequence)',
    'CREATE INDEX ix_agent_message_tool_call ON public.agent_messages USING btree (tool_call_id)',
    'CREATE INDEX ix_agent_messages_agent_run_id ON public.agent_messages USING btree (agent_run_id)',
    'CREATE INDEX ix_agent_messages_conversation_id ON public.agent_messages USING btree (conversation_id)',
    'CREATE INDEX ix_agent_messages_id ON public.agent_messages USING btree (id)',
    'CREATE INDEX ix_agent_messages_role ON public.agent_messages USING btree (role)',
    'CREATE INDEX ix_agent_pod_name ON public.agents USING btree (pod_id, name)',
    'CREATE INDEX ix_agent_run_conversation_created ON public.agent_runs USING btree (conversation_id, created_at)',
    'CREATE INDEX ix_agent_run_conversation_status ON public.agent_runs USING btree (conversation_id, status)',
    'CREATE INDEX ix_agent_runs_agent_id ON public.agent_runs USING btree (agent_id)',
    'CREATE INDEX ix_agent_runs_conversation_id ON public.agent_runs USING btree (conversation_id)',
    'CREATE INDEX ix_agent_runs_id ON public.agent_runs USING btree (id)',
    'CREATE INDEX ix_agent_runs_parent_run_id ON public.agent_runs USING btree (parent_run_id)',
    'CREATE INDEX ix_agent_runs_status ON public.agent_runs USING btree (status)',
    'CREATE INDEX ix_agent_runtime_daemons_user_status ON public.agent_runtime_daemons USING btree (user_id, status)',
    'CREATE INDEX ix_agent_runtime_profile_org_scope_status ON public.agent_runtime_profiles USING btree (organization_id, scope, status)',
    'CREATE INDEX ix_agent_runtime_profile_org_status ON public.agent_runtime_profiles USING btree (organization_id, status)',
    'CREATE INDEX ix_agent_runtime_profiles_daemon_id ON public.agent_runtime_profiles USING btree (daemon_id)',
    'CREATE INDEX ix_agent_runtime_profiles_id ON public.agent_runtime_profiles USING btree (id)',
    'CREATE INDEX ix_agent_runtime_profiles_organization_id ON public.agent_runtime_profiles USING btree (organization_id)',
    'CREATE INDEX ix_agent_runtime_profiles_user_id ON public.agent_runtime_profiles USING btree (user_id)',
    'CREATE INDEX ix_agent_surface_conversation_links_conversation_id ON public.agent_surface_conversation_links USING btree (conversation_id)',
    'CREATE INDEX ix_agent_surface_conversation_links_id ON public.agent_surface_conversation_links USING btree (id)',
    'CREATE INDEX ix_agent_surface_conversation_links_platform ON public.agent_surface_conversation_links USING btree (platform)',
    'CREATE INDEX ix_agent_surface_conversation_links_surface_id ON public.agent_surface_conversation_links USING btree (surface_id)',
    'CREATE UNIQUE INDEX ix_agent_surface_external_user_platform_tenant_external ON public.agent_surface_external_users USING btree (platform, tenant_id, external_user_id)',
    'CREATE INDEX ix_agent_surface_external_users_email ON public.agent_surface_external_users USING btree (email)',
    'CREATE INDEX ix_agent_surface_external_users_id ON public.agent_surface_external_users USING btree (id)',
    'CREATE INDEX ix_agent_surface_external_users_phone ON public.agent_surface_external_users USING btree (phone)',
    'CREATE INDEX ix_agent_surface_external_users_platform ON public.agent_surface_external_users USING btree (platform)',
    'CREATE INDEX ix_agent_surface_external_users_resolved_user_id ON public.agent_surface_external_users USING btree (resolved_user_id)',
    'CREATE INDEX ix_agent_surface_link_conversation ON public.agent_surface_conversation_links USING btree (conversation_id)',
    'CREATE UNIQUE INDEX ix_agent_surface_link_external_thread ON public.agent_surface_conversation_links USING btree (surface_id, platform, external_channel_id, external_thread_id, external_user_id)',
    'CREATE INDEX ix_agent_surface_links_route_key ON public.agent_surface_conversation_links USING btree (route_key)',
    'CREATE INDEX ix_agent_surface_links_routed_agent_id ON public.agent_surface_conversation_links USING btree (routed_agent_id)',
    'CREATE INDEX ix_agent_surfaces_account_id ON public.agent_surfaces USING btree (account_id)',
    'CREATE INDEX ix_agent_surfaces_agent_id ON public.agent_surfaces USING btree (agent_id)',
    'CREATE INDEX ix_agent_surfaces_credential_mode ON public.agent_surfaces USING btree (credential_mode)',
    'CREATE INDEX ix_agent_surfaces_event_mode ON public.agent_surfaces USING btree (event_mode)',
    'CREATE INDEX ix_agent_surfaces_external_channel_id ON public.agent_surfaces USING btree (external_channel_id)',
    'CREATE INDEX ix_agent_surfaces_external_tenant_id ON public.agent_surfaces USING btree (external_tenant_id)',
    'CREATE INDEX ix_agent_surfaces_external_workspace_id ON public.agent_surfaces USING btree (external_workspace_id)',
    'CREATE INDEX ix_agent_surfaces_id ON public.agent_surfaces USING btree (id)',
    'CREATE INDEX ix_agent_surfaces_mode ON public.agent_surfaces USING btree (mode)',
    'CREATE INDEX ix_agent_surfaces_pod_id ON public.agent_surfaces USING btree (pod_id)',
    'CREATE INDEX ix_agent_surfaces_schedule_id ON public.agent_surfaces USING btree (schedule_id)',
    'CREATE INDEX ix_agent_surfaces_surface_identity_email ON public.agent_surfaces USING btree (surface_identity_email)',
    'CREATE INDEX ix_agent_surfaces_surface_identity_id ON public.agent_surfaces USING btree (surface_identity_id)',
    'CREATE INDEX ix_agent_surfaces_surface_identity_username ON public.agent_surfaces USING btree (surface_identity_username)',
    'CREATE INDEX ix_agent_surfaces_surface_type ON public.agent_surfaces USING btree (surface_type)',
    'CREATE INDEX ix_agents_id ON public.agents USING btree (id)',
    'CREATE INDEX ix_agents_name ON public.agents USING btree (name)',
    'CREATE INDEX ix_agents_pod_id ON public.agents USING btree (pod_id)',
    'CREATE INDEX ix_agents_user_id ON public.agents USING btree (user_id)',
    'CREATE UNIQUE INDEX ix_connector_operations_app_provider_name ON public.connector_operations USING btree (connector_id, provider, name)',
    'CREATE INDEX ix_connector_operations_app_provider_operation ON public.connector_operations USING btree (connector_id, provider, provider_operation_name)',
    'CREATE INDEX ix_connector_operations_id ON public.connector_operations USING btree (id)',
    "CREATE INDEX ix_connector_operations_search_document_fts ON public.connector_operations USING gin (to_tsvector('english'::regconfig, COALESCE(search_document, ''::text)))",
    'CREATE UNIQUE INDEX ix_connector_triggers_app_provider_event ON public.connector_triggers USING btree (connector_id, provider, event_type)',
    'CREATE INDEX ix_connector_triggers_id ON public.connector_triggers USING btree (id)',
    'CREATE INDEX ix_connectors_id ON public.connectors USING btree (id)',
    'CREATE INDEX ix_assistant_pod_name ON public.assistants USING btree (pod_id, name)',
    'CREATE INDEX ix_assistants_id ON public.assistants USING btree (id)',
    'CREATE INDEX ix_assistants_name ON public.assistants USING btree (name)',
    'CREATE INDEX ix_assistants_pod_id ON public.assistants USING btree (pod_id)',
    'CREATE INDEX ix_assistants_user_id ON public.assistants USING btree (user_id)',
    'CREATE INDEX ix_auth_configs_app_provider_status ON public.auth_configs USING btree (connector_id, provider, status)',
    'CREATE INDEX ix_auth_configs_id ON public.auth_configs USING btree (id)',
    'CREATE INDEX ix_auth_configs_org_status ON public.auth_configs USING btree (organization_id, status)',
    "CREATE UNIQUE INDEX ix_auth_configs_unique_active_org_app ON public.auth_configs USING btree (organization_id, connector_id) WHERE ((status)::text = 'ACTIVE'::text)",
    "CREATE UNIQUE INDEX ix_auth_configs_unique_active_org_name ON public.auth_configs USING btree (organization_id, name) WHERE ((status)::text = 'ACTIVE'::text)",
    'CREATE INDEX ix_auth_permissions_id ON public.auth_permissions USING btree (id)',
    'CREATE INDEX ix_connect_requests_id ON public.connect_requests USING btree (id)',
    'CREATE INDEX ix_conversation_messages_conversation_id ON public.conversation_messages USING btree (conversation_id)',
    'CREATE INDEX ix_conversation_messages_external_user_id ON public.conversation_messages USING btree (external_user_id)',
    'CREATE INDEX ix_conversation_messages_id ON public.conversation_messages USING btree (id)',
    'CREATE INDEX ix_conversation_messages_user_id ON public.conversation_messages USING btree (user_id)',
    'CREATE INDEX ix_conversations_assistant_id ON public.conversations USING btree (assistant_id)',
    'CREATE INDEX ix_conversations_external_thread_id ON public.conversations USING btree (external_thread_id)',
    'CREATE INDEX ix_conversations_id ON public.conversations USING btree (id)',
    'CREATE INDEX ix_conversations_organization_id ON public.conversations USING btree (organization_id)',
    'CREATE INDEX ix_conversations_pod_id ON public.conversations USING btree (pod_id)',
    'CREATE INDEX ix_conversations_surface_installation_id ON public.conversations USING btree (surface_installation_id)',
    'CREATE INDEX ix_conversations_surface_type ON public.conversations USING btree (surface_type)',
    'CREATE INDEX ix_conversations_user_id ON public.conversations USING btree (user_id)',
    'CREATE UNIQUE INDEX ix_datastore_file_pod_path ON public.datastore_files USING btree (pod_id, path)',
    'CREATE INDEX ix_datastore_file_pod_path_prefix ON public.datastore_files USING btree (pod_id, path text_pattern_ops)',
    'CREATE INDEX ix_datastore_file_status ON public.datastore_files USING btree (pod_id, status)',
    'CREATE INDEX ix_datastore_files_id ON public.datastore_files USING btree (id)',
    'CREATE INDEX ix_datastore_files_owner_user_id ON public.datastore_files USING btree (owner_user_id)',
    'CREATE INDEX ix_datastore_files_pod_id ON public.datastore_files USING btree (pod_id)',
    'CREATE UNIQUE INDEX ix_datastore_table_pod_name ON public.datastore_tables USING btree (pod_id, table_name)',
    'CREATE INDEX ix_datastore_tables_id ON public.datastore_tables USING btree (id)',
    'CREATE INDEX ix_datastore_tables_pod_id ON public.datastore_tables USING btree (pod_id)',
    'CREATE INDEX ix_app_name ON public.apps USING btree (name)',
    'CREATE INDEX ix_app_pod_name ON public.apps USING btree (pod_id, name)',
    'CREATE INDEX ix_app_public_slug ON public.apps USING btree (public_slug)',
    'CREATE INDEX ix_app_release_app_id ON public.app_releases USING btree (app_id)',
    'CREATE INDEX ix_app_releases_id ON public.app_releases USING btree (id)',
    'CREATE INDEX ix_apps_id ON public.apps USING btree (id)',
    'CREATE INDEX ix_function_name ON public.functions USING btree (name)',
    'CREATE INDEX ix_function_pod_name ON public.functions USING btree (pod_id, name)',
    'CREATE INDEX ix_function_runs_id ON public.function_runs USING btree (id)',
    'CREATE INDEX ix_functions_id ON public.functions USING btree (id)',
    'CREATE UNIQUE INDEX ix_org_invitation_email_org ON public.organization_invitations USING btree (email, organization_id)',
    'CREATE INDEX ix_org_member_org_role ON public.organization_members USING btree (organization_id, role)',
    'CREATE UNIQUE INDEX ix_org_member_user_org ON public.organization_members USING btree (user_id, organization_id)',
    'CREATE INDEX ix_organization_invitations_email ON public.organization_invitations USING btree (email)',
    'CREATE INDEX ix_organization_invitations_id ON public.organization_invitations USING btree (id)',
    'CREATE INDEX ix_organization_invitations_status ON public.organization_invitations USING btree (status)',
    'CREATE INDEX ix_organization_members_id ON public.organization_members USING btree (id)',
    'CREATE UNIQUE INDEX ix_organizations_email_domain ON public.organizations USING btree (email_domain)',
    'CREATE INDEX ix_organizations_id ON public.organizations USING btree (id)',
    'CREATE UNIQUE INDEX ix_organizations_name ON public.organizations USING btree (name)',
    'CREATE UNIQUE INDEX ix_organizations_slug ON public.organizations USING btree (slug)',
    'CREATE INDEX ix_pod_join_request_org_status ON public.pod_join_requests USING btree (organization_id, status)',
    'CREATE INDEX ix_pod_join_request_pod_user_status ON public.pod_join_requests USING btree (pod_id, user_id, status)',
    'CREATE INDEX ix_pod_join_requests_approved_by_user_id ON public.pod_join_requests USING btree (approved_by_user_id)',
    'CREATE INDEX ix_pod_join_requests_id ON public.pod_join_requests USING btree (id)',
    'CREATE INDEX ix_pod_join_requests_organization_id ON public.pod_join_requests USING btree (organization_id)',
    'CREATE INDEX ix_pod_join_requests_pod_id ON public.pod_join_requests USING btree (pod_id)',
    'CREATE INDEX ix_pod_join_requests_status ON public.pod_join_requests USING btree (status)',
    'CREATE INDEX ix_pod_join_requests_user_id ON public.pod_join_requests USING btree (user_id)',
    'CREATE UNIQUE INDEX ix_pod_member_pod_org_member ON public.pod_members USING btree (pod_id, organization_member_id)',
    'CREATE INDEX ix_pod_members_id ON public.pod_members USING btree (id)',
    'CREATE INDEX ix_pod_org_name ON public.pods USING btree (organization_id, name)',
    'CREATE INDEX ix_pod_user_name ON public.pods USING btree (user_id, name)',
    'CREATE INDEX ix_pods_id ON public.pods USING btree (id)',
    'CREATE INDEX ix_pods_is_deleted ON public.pods USING btree (is_deleted)',
    'CREATE INDEX ix_pods_name ON public.pods USING btree (name)',
    'CREATE INDEX ix_pods_organization_id ON public.pods USING btree (organization_id)',
    'CREATE INDEX ix_pods_user_id ON public.pods USING btree (user_id)',
    'CREATE INDEX ix_resource_permission_grants_grantee ON public.resource_permission_grants USING btree (pod_id, grantee_type, grantee_id, permission_id)',
    'CREATE INDEX ix_resource_permission_grants_id ON public.resource_permission_grants USING btree (id)',
    'CREATE INDEX ix_resource_permission_grants_resource ON public.resource_permission_grants USING btree (pod_id, resource_type, resource_id)',
    'CREATE INDEX ix_role_assignments_id ON public.role_assignments USING btree (id)',
    'CREATE INDEX ix_role_assignments_principal ON public.role_assignments USING btree (principal_type, principal_id)',
    'CREATE INDEX ix_role_assignments_role_id ON public.role_assignments USING btree (role_id)',
    'CREATE INDEX ix_role_permissions_id ON public.role_permissions USING btree (id)',
    'CREATE INDEX ix_role_permissions_permission ON public.role_permissions USING btree (permission_id)',
    'CREATE INDEX ix_roles_id ON public.roles USING btree (id)',
    'CREATE INDEX ix_roles_org_pod ON public.roles USING btree (organization_id, pod_id)',
    'CREATE INDEX ix_rpg_grantee_resource_permission ON public.resource_permission_grants USING btree (pod_id, grantee_type, grantee_id, resource_type, permission_id, resource_id)',
    'CREATE INDEX ix_rpg_resource_permission_grantee ON public.resource_permission_grants USING btree (pod_id, resource_type, resource_id, permission_id, grantee_type, grantee_id)',
    'CREATE INDEX ix_schedules_account ON public.schedules USING btree (account_id)',
    'CREATE INDEX ix_schedules_agent ON public.schedules USING btree (agent_id)',
    'CREATE INDEX ix_schedules_agent_id ON public.schedules USING btree (agent_id)',
    'CREATE INDEX ix_schedules_connector_trigger ON public.schedules USING btree (connector_trigger_id)',
    'CREATE INDEX ix_schedules_config_gin ON public.schedules USING gin (config)',
    'CREATE INDEX ix_schedules_is_active ON public.schedules USING btree (is_active)',
    'CREATE INDEX ix_schedules_is_internal ON public.schedules USING btree (is_internal)',
    'CREATE INDEX ix_schedules_name ON public.schedules USING btree (name)',
    'CREATE INDEX ix_schedules_pod_id ON public.schedules USING btree (pod_id)',
    'CREATE INDEX ix_schedules_schedule_type ON public.schedules USING btree (schedule_type)',
    'CREATE INDEX ix_schedules_type_active ON public.schedules USING btree (schedule_type, is_active)',
    'CREATE INDEX ix_schedules_user_id ON public.schedules USING btree (user_id)',
    'CREATE INDEX ix_schedules_user_pod ON public.schedules USING btree (user_id, pod_id)',
    'CREATE INDEX ix_schedules_workflow ON public.schedules USING btree (workflow_id)',
    'CREATE INDEX ix_schedules_workflow_id ON public.schedules USING btree (workflow_id)',
    'CREATE INDEX ix_triggers_id ON public.schedules USING btree (id)',
    'CREATE UNIQUE INDEX ix_unique_user_auth_config_account ON public.accounts USING btree (user_id, auth_config_id)',
    'CREATE INDEX ix_usage_agent_run_time ON public.usage_records USING btree (agent_run_id, occurred_at)',
    'CREATE INDEX ix_usage_agent_time ON public.usage_records USING btree (agent_id, occurred_at)',
    'CREATE INDEX ix_usage_limit_counters_organization_id ON public.usage_limit_counters USING btree (organization_id)',
    'CREATE INDEX ix_usage_limit_counters_user_id ON public.usage_limit_counters USING btree (user_id)',
    'CREATE INDEX ix_usage_limit_counters_window_kind ON public.usage_limit_counters USING btree (window_kind)',
    'CREATE INDEX ix_usage_org_profile_scope_time ON public.usage_records USING btree (organization_id, profile_scope, occurred_at)',
    'CREATE INDEX ix_usage_org_profile_time ON public.usage_records USING btree (organization_id, profile_id, occurred_at)',
    'CREATE INDEX ix_usage_org_time ON public.usage_records USING btree (organization_id, occurred_at)',
    'CREATE INDEX ix_usage_org_user_profile_scope_time ON public.usage_records USING btree (organization_id, user_id, profile_scope, occurred_at)',
    'CREATE INDEX ix_usage_pod_time ON public.usage_records USING btree (pod_id, occurred_at)',
    'CREATE INDEX ix_usage_records_agent_id ON public.usage_records USING btree (agent_id)',
    'CREATE INDEX ix_usage_records_agent_run_id ON public.usage_records USING btree (agent_run_id)',
    'CREATE INDEX ix_usage_records_conversation_id ON public.usage_records USING btree (conversation_id)',
    'CREATE INDEX ix_usage_records_id ON public.usage_records USING btree (id)',
    'CREATE INDEX ix_usage_records_model_name ON public.usage_records USING btree (model_name)',
    'CREATE INDEX ix_usage_records_occurred_at ON public.usage_records USING btree (occurred_at)',
    'CREATE INDEX ix_usage_records_organization_id ON public.usage_records USING btree (organization_id)',
    'CREATE INDEX ix_usage_records_parent_agent_run_id ON public.usage_records USING btree (parent_agent_run_id)',
    'CREATE INDEX ix_usage_records_pod_id ON public.usage_records USING btree (pod_id)',
    'CREATE INDEX ix_usage_records_profile_id ON public.usage_records USING btree (profile_id)',
    'CREATE INDEX ix_usage_records_profile_scope ON public.usage_records USING btree (profile_scope)',
    'CREATE INDEX ix_usage_records_source_id ON public.usage_records USING btree (source_id)',
    'CREATE INDEX ix_usage_records_source_type ON public.usage_records USING btree (source_type)',
    'CREATE INDEX ix_usage_records_usage_kind ON public.usage_records USING btree (usage_kind)',
    'CREATE INDEX ix_usage_records_user_id ON public.usage_records USING btree (user_id)',
    'CREATE INDEX ix_usage_source_time ON public.usage_records USING btree (source_type, source_id, occurred_at)',
    'CREATE INDEX ix_usage_user_time ON public.usage_records USING btree (user_id, occurred_at)',
    'CREATE UNIQUE INDEX ix_users_email ON public.users USING btree (email)',
    'CREATE INDEX ix_users_id ON public.users USING btree (id)',
    'CREATE INDEX ix_users_mobile_number ON public.users USING btree (mobile_number)',
    'CREATE INDEX ix_users_telegram_username ON public.users USING btree (telegram_username)',
    'CREATE INDEX ix_workflow_flow_pod_name ON public.workflow_flows USING btree (pod_id, name)',
    'CREATE INDEX ix_workflow_flow_runs_flow_id ON public.workflow_flow_runs USING btree (flow_id)',
    'CREATE INDEX ix_workflow_flow_runs_id ON public.workflow_flow_runs USING btree (id)',
    'CREATE INDEX ix_workflow_flow_runs_pod_id ON public.workflow_flow_runs USING btree (pod_id)',
    'CREATE INDEX ix_workflow_flow_runs_schedule_event_id ON public.workflow_flow_runs USING btree (schedule_event_id)',
    'CREATE INDEX ix_workflow_flow_runs_user_id ON public.workflow_flow_runs USING btree (user_id)',
    'CREATE INDEX ix_workflow_flows_id ON public.workflow_flows USING btree (id)',
    'CREATE INDEX ix_workflow_flows_pod_id ON public.workflow_flows USING btree (pod_id)',
    'CREATE INDEX ix_workflow_run_waits_assigned_pod_member_id ON public.workflow_run_waits USING btree (assigned_pod_member_id)',
    'CREATE INDEX ix_workflow_run_waits_assignee_status ON public.workflow_run_waits USING btree (assigned_pod_member_id, status)',
    'CREATE INDEX ix_workflow_run_waits_external_ref ON public.workflow_run_waits USING btree (external_ref)',
    'CREATE INDEX ix_workflow_run_waits_flow_id ON public.workflow_run_waits USING btree (flow_id)',
    'CREATE INDEX ix_workflow_run_waits_id ON public.workflow_run_waits USING btree (id)',
    'CREATE INDEX ix_workflow_run_waits_pod_id ON public.workflow_run_waits USING btree (pod_id)',
    'CREATE INDEX ix_workflow_run_waits_run_id ON public.workflow_run_waits USING btree (run_id)',
    'CREATE INDEX ix_workflow_run_waits_run_status ON public.workflow_run_waits USING btree (run_id, status)',
    'CREATE INDEX ix_workflow_run_waits_status ON public.workflow_run_waits USING btree (status)',
    'CREATE INDEX ix_workflow_run_waits_type_ref_status ON public.workflow_run_waits USING btree (wait_type, external_ref, status)',
    'CREATE INDEX ix_workflow_run_waits_wait_type ON public.workflow_run_waits USING btree (wait_type)',
    "CREATE UNIQUE INDEX uq_agent_active_run_per_conversation ON public.agent_runs USING btree (conversation_id) WHERE ((status)::text = ANY ((ARRAY['RUNNING'::character varying, 'STOP_REQUESTED'::character varying])::text[]))",
    "CREATE UNIQUE INDEX uq_agent_runtime_profile_org_name ON public.agent_runtime_profiles USING btree (organization_id, name) WHERE ((scope)::text = 'ORGANIZATION'::text)",
    "CREATE UNIQUE INDEX uq_agent_runtime_profile_personal_name ON public.agent_runtime_profiles USING btree (organization_id, user_id, name) WHERE ((scope)::text = 'PERSONAL'::text)",
    'CREATE UNIQUE INDEX uq_pod_active_org_name ON public.pods USING btree (organization_id, name) WHERE (is_deleted = false)',
    'CREATE UNIQUE INDEX uq_roles_org_name ON public.roles USING btree (organization_id, name) WHERE (pod_id IS NULL)',
    'CREATE UNIQUE INDEX uq_roles_pod_name ON public.roles USING btree (pod_id, name) WHERE (pod_id IS NOT NULL)',
    'CREATE UNIQUE INDEX uq_schedules_pod_name ON public.schedules USING btree (pod_id, name) WHERE ((pod_id IS NOT NULL) AND (name IS NOT NULL) AND (is_internal = false))',
    'CREATE UNIQUE INDEX uq_usage_limit_counter_window ON public.usage_limit_counters USING btree (organization_id, user_id, window_kind, window_start)',
    "CREATE UNIQUE INDEX uq_workflow_run_waits_one_active ON public.workflow_run_waits USING btree (run_id) WHERE ((status)::text = 'ACTIVE'::text)",
    'CREATE UNIQUE INDEX ux_agent_surfaces_pod_surface_type ON public.agent_surfaces USING btree (pod_id, surface_type)',
    "CREATE UNIQUE INDEX ux_users_mobile_number_digits ON public.users USING btree (regexp_replace((mobile_number)::text, '\\D'::text, ''::text, 'g'::text)) WHERE ((mobile_number IS NOT NULL) AND (regexp_replace((mobile_number)::text, '\\D'::text, ''::text, 'g'::text) <> ''::text))",
    'CREATE UNIQUE INDEX ux_users_telegram_username_lower ON public.users USING btree (lower((telegram_username)::text)) WHERE (telegram_username IS NOT NULL)',
    'ALTER TABLE ONLY public.accounts\n    ADD CONSTRAINT accounts_connector_id_fkey FOREIGN KEY (connector_id) REFERENCES public.connectors(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.accounts\n    ADD CONSTRAINT accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.agent_approval_decisions\n    ADD CONSTRAINT agent_approval_decisions_agent_run_id_fkey FOREIGN KEY (agent_run_id) REFERENCES public.agent_runs(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.agent_approval_decisions\n    ADD CONSTRAINT agent_approval_decisions_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.agent_conversations(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.agent_approval_decisions\n    ADD CONSTRAINT agent_approval_decisions_resolved_by_user_id_fkey FOREIGN KEY (resolved_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.agent_conversations\n    ADD CONSTRAINT agent_conversations_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.agent_conversations\n    ADD CONSTRAINT agent_conversations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.agent_conversations\n    ADD CONSTRAINT agent_conversations_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.agent_conversations(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.agent_conversations\n    ADD CONSTRAINT agent_conversations_pod_id_fkey FOREIGN KEY (pod_id) REFERENCES public.pods(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.agent_conversations\n    ADD CONSTRAINT agent_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.agent_feedback\n    ADD CONSTRAINT agent_feedback_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.agent_feedback\n    ADD CONSTRAINT agent_feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.agent_messages\n    ADD CONSTRAINT agent_messages_agent_run_id_fkey FOREIGN KEY (agent_run_id) REFERENCES public.agent_runs(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.agent_messages\n    ADD CONSTRAINT agent_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.agent_conversations(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.agent_runs\n    ADD CONSTRAINT agent_runs_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.agent_runs\n    ADD CONSTRAINT agent_runs_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.agent_conversations(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.agent_runs\n    ADD CONSTRAINT agent_runs_parent_run_id_fkey FOREIGN KEY (parent_run_id) REFERENCES public.agent_runs(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.agent_runtime_daemons\n    ADD CONSTRAINT agent_runtime_daemons_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.agent_runtime_profiles\n    ADD CONSTRAINT agent_runtime_profiles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.agent_surface_conversation_links\n    ADD CONSTRAINT agent_surface_conversation_links_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.agent_conversations(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.agent_surface_conversation_links\n    ADD CONSTRAINT agent_surface_conversation_links_surface_id_fkey FOREIGN KEY (surface_id) REFERENCES public.agent_surfaces(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.agent_surfaces\n    ADD CONSTRAINT agent_surfaces_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.agent_surfaces\n    ADD CONSTRAINT agent_surfaces_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.schedules(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.agents\n    ADD CONSTRAINT agents_pod_id_fkey FOREIGN KEY (pod_id) REFERENCES public.pods(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.agents\n    ADD CONSTRAINT agents_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.connector_operations\n    ADD CONSTRAINT connector_operations_connector_id_fkey FOREIGN KEY (connector_id) REFERENCES public.connectors(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.connector_triggers\n    ADD CONSTRAINT connector_triggers_connector_id_fkey FOREIGN KEY (connector_id) REFERENCES public.connectors(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.agent_surface_external_users\n    ADD CONSTRAINT assistant_surface_external_users_resolved_user_id_fkey FOREIGN KEY (resolved_user_id) REFERENCES public.users(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.agent_surfaces\n    ADD CONSTRAINT assistant_surfaces_pod_id_fkey FOREIGN KEY (pod_id) REFERENCES public.pods(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.agent_surfaces\n    ADD CONSTRAINT assistant_surfaces_trigger_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.schedules(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.assistants\n    ADD CONSTRAINT assistants_pod_id_fkey FOREIGN KEY (pod_id) REFERENCES public.pods(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.assistants\n    ADD CONSTRAINT assistants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.auth_configs\n    ADD CONSTRAINT auth_configs_connector_id_fkey FOREIGN KEY (connector_id) REFERENCES public.connectors(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.auth_configs\n    ADD CONSTRAINT auth_configs_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.auth_configs\n    ADD CONSTRAINT auth_configs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.auth_configs\n    ADD CONSTRAINT auth_configs_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.connect_requests\n    ADD CONSTRAINT connect_requests_connector_id_fkey FOREIGN KEY (connector_id) REFERENCES public.connectors(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.connect_requests\n    ADD CONSTRAINT connect_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.conversation_messages\n    ADD CONSTRAINT conversation_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.conversation_messages\n    ADD CONSTRAINT conversation_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.conversations\n    ADD CONSTRAINT conversations_assistant_id_fkey FOREIGN KEY (assistant_id) REFERENCES public.assistants(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.conversations\n    ADD CONSTRAINT conversations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.conversations\n    ADD CONSTRAINT conversations_pod_id_fkey FOREIGN KEY (pod_id) REFERENCES public.pods(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.conversations\n    ADD CONSTRAINT conversations_surface_installation_id_fkey FOREIGN KEY (surface_installation_id) REFERENCES public.agent_surfaces(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.conversations\n    ADD CONSTRAINT conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.datastore_files\n    ADD CONSTRAINT datastore_files_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.users(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.datastore_files\n    ADD CONSTRAINT datastore_files_pod_id_fkey FOREIGN KEY (pod_id) REFERENCES public.pods(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.datastore_tables\n    ADD CONSTRAINT datastore_tables_pod_id_fkey FOREIGN KEY (pod_id) REFERENCES public.pods(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.datastore_tables\n    ADD CONSTRAINT datastore_tables_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.app_releases\n    ADD CONSTRAINT app_releases_app_id_fkey FOREIGN KEY (app_id) REFERENCES public.apps(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.apps\n    ADD CONSTRAINT apps_pod_id_fkey FOREIGN KEY (pod_id) REFERENCES public.pods(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.apps\n    ADD CONSTRAINT apps_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.accounts\n    ADD CONSTRAINT fk_accounts_auth_config_id_auth_configs FOREIGN KEY (auth_config_id) REFERENCES public.auth_configs(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.accounts\n    ADD CONSTRAINT fk_accounts_organization_id_organizations FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.agent_runtime_profiles\n    ADD CONSTRAINT fk_agent_runtime_profiles_daemon_id_agent_runtime_daemons FOREIGN KEY (daemon_id) REFERENCES public.agent_runtime_daemons(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.agent_runtime_profiles\n    ADD CONSTRAINT fk_agent_runtime_profiles_user_id_users FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.agent_surface_conversation_links\n    ADD CONSTRAINT fk_agent_surface_links_routed_agent_id_agents FOREIGN KEY (routed_agent_id) REFERENCES public.agents(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.agent_surfaces\n    ADD CONSTRAINT fk_agent_surfaces_account_id_accounts FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.connect_requests\n    ADD CONSTRAINT fk_connect_requests_auth_config_id_auth_configs FOREIGN KEY (auth_config_id) REFERENCES public.auth_configs(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.connect_requests\n    ADD CONSTRAINT fk_connect_requests_organization_id_organizations FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.schedules\n    ADD CONSTRAINT fk_schedules_agent_id_agents FOREIGN KEY (agent_id) REFERENCES public.agents(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.schedules\n    ADD CONSTRAINT fk_schedules_workflow_id_workflow_flows FOREIGN KEY (workflow_id) REFERENCES public.workflow_flows(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.function_runs\n    ADD CONSTRAINT function_runs_function_id_fkey FOREIGN KEY (function_id) REFERENCES public.functions(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.function_runs\n    ADD CONSTRAINT function_runs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.functions\n    ADD CONSTRAINT functions_pod_id_fkey FOREIGN KEY (pod_id) REFERENCES public.pods(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.functions\n    ADD CONSTRAINT functions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.organization_invitations\n    ADD CONSTRAINT organization_invitations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.organization_invitations\n    ADD CONSTRAINT organization_invitations_pod_id_fkey FOREIGN KEY (pod_id) REFERENCES public.pods(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.organization_members\n    ADD CONSTRAINT organization_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.organization_members\n    ADD CONSTRAINT organization_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.pod_join_requests\n    ADD CONSTRAINT pod_join_requests_approved_by_user_id_fkey FOREIGN KEY (approved_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.pod_join_requests\n    ADD CONSTRAINT pod_join_requests_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.pod_join_requests\n    ADD CONSTRAINT pod_join_requests_pod_id_fkey FOREIGN KEY (pod_id) REFERENCES public.pods(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.pod_join_requests\n    ADD CONSTRAINT pod_join_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.pod_members\n    ADD CONSTRAINT pod_members_organization_member_id_fkey FOREIGN KEY (organization_member_id) REFERENCES public.organization_members(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.pod_members\n    ADD CONSTRAINT pod_members_pod_id_fkey FOREIGN KEY (pod_id) REFERENCES public.pods(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.pods\n    ADD CONSTRAINT pods_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.pods\n    ADD CONSTRAINT pods_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.resource_permission_grants\n    ADD CONSTRAINT resource_permission_grants_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.resource_permission_grants\n    ADD CONSTRAINT resource_permission_grants_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.auth_permissions(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.resource_permission_grants\n    ADD CONSTRAINT resource_permission_grants_pod_id_fkey FOREIGN KEY (pod_id) REFERENCES public.pods(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.role_assignments\n    ADD CONSTRAINT role_assignments_assigned_by_user_id_fkey FOREIGN KEY (assigned_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.role_assignments\n    ADD CONSTRAINT role_assignments_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.role_permissions\n    ADD CONSTRAINT role_permissions_granted_by_user_id_fkey FOREIGN KEY (granted_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.role_permissions\n    ADD CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.auth_permissions(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.role_permissions\n    ADD CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.roles\n    ADD CONSTRAINT roles_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.roles\n    ADD CONSTRAINT roles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.roles\n    ADD CONSTRAINT roles_pod_id_fkey FOREIGN KEY (pod_id) REFERENCES public.pods(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.schedules\n    ADD CONSTRAINT triggers_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.schedules\n    ADD CONSTRAINT triggers_connector_trigger_id_fkey FOREIGN KEY (connector_trigger_id) REFERENCES public.connector_triggers(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.schedules\n    ADD CONSTRAINT triggers_pod_id_fkey FOREIGN KEY (pod_id) REFERENCES public.pods(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.schedules\n    ADD CONSTRAINT triggers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.workflow_flow_runs\n    ADD CONSTRAINT workflow_flow_runs_flow_id_fkey FOREIGN KEY (flow_id) REFERENCES public.workflow_flows(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.workflow_flow_runs\n    ADD CONSTRAINT workflow_flow_runs_pod_id_fkey FOREIGN KEY (pod_id) REFERENCES public.pods(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.workflow_flow_runs\n    ADD CONSTRAINT workflow_flow_runs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.workflow_flows\n    ADD CONSTRAINT workflow_flows_pod_id_fkey FOREIGN KEY (pod_id) REFERENCES public.pods(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.workflow_flows\n    ADD CONSTRAINT workflow_flows_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.workflow_run_waits\n    ADD CONSTRAINT workflow_run_waits_assigned_pod_member_id_fkey FOREIGN KEY (assigned_pod_member_id) REFERENCES public.pod_members(id) ON DELETE SET NULL',
    'ALTER TABLE ONLY public.workflow_run_waits\n    ADD CONSTRAINT workflow_run_waits_flow_id_fkey FOREIGN KEY (flow_id) REFERENCES public.workflow_flows(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.workflow_run_waits\n    ADD CONSTRAINT workflow_run_waits_pod_id_fkey FOREIGN KEY (pod_id) REFERENCES public.pods(id) ON DELETE CASCADE',
    'ALTER TABLE ONLY public.workflow_run_waits\n    ADD CONSTRAINT workflow_run_waits_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.workflow_flow_runs(id) ON DELETE CASCADE',
]

_TABLES = ['accounts', 'agent_approval_decisions', 'agent_conversations', 'agent_feedback', 'agent_messages', 'agent_runs', 'agent_runtime_daemons', 'agent_runtime_profiles', 'agent_surface_conversation_links', 'agent_surface_external_users', 'agent_surfaces', 'agents', 'connector_operations', 'connector_triggers', 'connectors', 'assistants', 'auth_configs', 'auth_permissions', 'connect_requests', 'conversation_messages', 'conversations', 'datastore_files', 'datastore_tables', 'app_releases', 'apps', 'function_runs', 'functions', 'organization_invitations', 'organization_members', 'organizations', 'pod_join_requests', 'pod_members', 'pods', 'resource_permission_grants', 'role_assignments', 'role_permissions', 'roles', 'schedules', 'usage_limit_counters', 'usage_records', 'users', 'workflow_flow_runs', 'workflow_flows', 'workflow_run_waits']
_TYPES = []


def upgrade() -> None:
    for stmt in _STATEMENTS:
        op.execute(stmt)


def downgrade() -> None:
    for table in _TABLES:
        op.execute(f'DROP TABLE IF EXISTS "{table}" CASCADE')
    for type_name in _TYPES:
        op.execute(f'DROP TYPE IF EXISTS "{type_name}"')
