"""baseline schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-06-24 15:05:38.160706

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql
if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

# revision identifiers, used by Alembic.
revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_permissions',
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('resource_type', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('system_only', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_permissions_id'), 'auth_permissions', ['id'], unique=False)
    op.create_table('connectors',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=500), nullable=True),
    sa.Column('provider_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_instruction', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connectors_id'), 'connectors', ['id'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('email_domain', sa.String(length=255), nullable=True),
    sa.Column('join_policy', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_email_domain'), 'organizations', ['email_domain'], unique=True)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('usage_limit_counters',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('window_kind', sa.String(length=32), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_usd', sa.Float(), nullable=False),
    sa.Column('reserved_usd', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_limit_counters_id'), 'usage_limit_counters', ['id'], unique=False)
    op.create_index(op.f('ix_usage_limit_counters_organization_id'), 'usage_limit_counters', ['organization_id'], unique=False)
    op.create_index(op.f('ix_usage_limit_counters_user_id'), 'usage_limit_counters', ['user_id'], unique=False)
    op.create_index(op.f('ix_usage_limit_counters_window_kind'), 'usage_limit_counters', ['window_kind'], unique=False)
    op.create_index('uq_usage_limit_counter_window', 'usage_limit_counters', ['organization_id', 'user_id', 'window_kind', 'window_start'], unique=True)
    op.create_table('usage_records',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('pod_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('parent_agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('source_id', sa.String(length=120), nullable=True),
    sa.Column('profile_id', sa.String(length=120), nullable=False),
    sa.Column('profile_scope', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=160), nullable=False),
    sa.Column('usage_kind', sa.String(length=40), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_agent_run_time', 'usage_records', ['agent_run_id', 'occurred_at'], unique=False)
    op.create_index('ix_usage_agent_time', 'usage_records', ['agent_id', 'occurred_at'], unique=False)
    op.create_index('ix_usage_org_profile_scope_time', 'usage_records', ['organization_id', 'profile_scope', 'occurred_at'], unique=False)
    op.create_index('ix_usage_org_profile_time', 'usage_records', ['organization_id', 'profile_id', 'occurred_at'], unique=False)
    op.create_index('ix_usage_org_time', 'usage_records', ['organization_id', 'occurred_at'], unique=False)
    op.create_index('ix_usage_org_user_profile_scope_time', 'usage_records', ['organization_id', 'user_id', 'profile_scope', 'occurred_at'], unique=False)
    op.create_index('ix_usage_pod_time', 'usage_records', ['pod_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_usage_records_agent_id'), 'usage_records', ['agent_id'], unique=False)
    op.create_index(op.f('ix_usage_records_agent_run_id'), 'usage_records', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_usage_records_conversation_id'), 'usage_records', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_usage_records_id'), 'usage_records', ['id'], unique=False)
    op.create_index(op.f('ix_usage_records_model_name'), 'usage_records', ['model_name'], unique=False)
    op.create_index(op.f('ix_usage_records_occurred_at'), 'usage_records', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_usage_records_organization_id'), 'usage_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_usage_records_parent_agent_run_id'), 'usage_records', ['parent_agent_run_id'], unique=False)
    op.create_index(op.f('ix_usage_records_pod_id'), 'usage_records', ['pod_id'], unique=False)
    op.create_index(op.f('ix_usage_records_profile_id'), 'usage_records', ['profile_id'], unique=False)
    op.create_index(op.f('ix_usage_records_profile_scope'), 'usage_records', ['profile_scope'], unique=False)
    op.create_index(op.f('ix_usage_records_source_id'), 'usage_records', ['source_id'], unique=False)
    op.create_index(op.f('ix_usage_records_source_type'), 'usage_records', ['source_type'], unique=False)
    op.create_index(op.f('ix_usage_records_usage_kind'), 'usage_records', ['usage_kind'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.create_index('ix_usage_source_time', 'usage_records', ['source_type', 'source_id', 'occurred_at'], unique=False)
    op.create_index('ix_usage_user_time', 'usage_records', ['user_id', 'occurred_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('mobile_number', sa.String(length=32), nullable=True),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=False)
    op.create_index(op.f('ix_users_telegram_username'), 'users', ['telegram_username'], unique=False)
    op.create_table('agent_runtime_daemons',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_key', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('harness_catalog', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_key', name='uq_agent_runtime_daemon_user_device')
    )
    op.create_index(op.f('ix_agent_runtime_daemons_id'), 'agent_runtime_daemons', ['id'], unique=False)
    op.create_index(op.f('ix_agent_runtime_daemons_status'), 'agent_runtime_daemons', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runtime_daemons_user_id'), 'agent_runtime_daemons', ['user_id'], unique=False)
    op.create_index('ix_agent_runtime_daemons_user_status', 'agent_runtime_daemons', ['user_id', 'status'], unique=False)
    op.create_table('agent_surface_external_users',
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=True),
    sa.Column('external_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('raw_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolved_user_id', sa.Uuid(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resolved_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_surface_external_user_platform_tenant_external', 'agent_surface_external_users', ['platform', 'tenant_id', 'external_user_id'], unique=True)
    op.create_index(op.f('ix_agent_surface_external_users_email'), 'agent_surface_external_users', ['email'], unique=False)
    op.create_index(op.f('ix_agent_surface_external_users_id'), 'agent_surface_external_users', ['id'], unique=False)
    op.create_index(op.f('ix_agent_surface_external_users_phone'), 'agent_surface_external_users', ['phone'], unique=False)
    op.create_index(op.f('ix_agent_surface_external_users_platform'), 'agent_surface_external_users', ['platform'], unique=False)
    op.create_index(op.f('ix_agent_surface_external_users_resolved_user_id'), 'agent_surface_external_users', ['resolved_user_id'], unique=False)
    op.create_table('auth_configs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('connector_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('config_source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('provider_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auth_configs_app_provider_status', 'auth_configs', ['connector_id', 'provider', 'status'], unique=False)
    op.create_index(op.f('ix_auth_configs_id'), 'auth_configs', ['id'], unique=False)
    op.create_index('ix_auth_configs_org_status', 'auth_configs', ['organization_id', 'status'], unique=False)
    op.create_index('ix_auth_configs_unique_active_org_app', 'auth_configs', ['organization_id', 'connector_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_index('ix_auth_configs_unique_active_org_name', 'auth_configs', ['organization_id', 'name'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('connector_operations',
    sa.Column('connector_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider_operation_name', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('search_document', sa.Text(), nullable=True),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_connector_operations_app_provider_name', 'connector_operations', ['connector_id', 'provider', 'name'], unique=True)
    op.create_index('ix_connector_operations_app_provider_operation', 'connector_operations', ['connector_id', 'provider', 'provider_operation_name'], unique=False)
    op.create_index(op.f('ix_connector_operations_id'), 'connector_operations', ['id'], unique=False)
    op.create_table('connector_triggers',
    sa.Column('connector_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload_example', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_connector_triggers_app_provider_event', 'connector_triggers', ['connector_id', 'provider', 'event_type'], unique=True)
    op.create_index(op.f('ix_connector_triggers_id'), 'connector_triggers', ['id'], unique=False)
    op.create_table('organization_members',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_org_member_org_role', 'organization_members', ['organization_id', 'role'], unique=False)
    op.create_index('ix_org_member_user_org', 'organization_members', ['user_id', 'organization_id'], unique=True)
    op.create_index(op.f('ix_organization_members_id'), 'organization_members', ['id'], unique=False)
    op.create_table('pods',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pod_org_name', 'pods', ['organization_id', 'name'], unique=False)
    op.create_index('ix_pod_user_name', 'pods', ['user_id', 'name'], unique=False)
    op.create_index(op.f('ix_pods_id'), 'pods', ['id'], unique=False)
    op.create_index(op.f('ix_pods_is_deleted'), 'pods', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_pods_name'), 'pods', ['name'], unique=False)
    op.create_index(op.f('ix_pods_organization_id'), 'pods', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pods_user_id'), 'pods', ['user_id'], unique=False)
    op.create_index('uq_pod_active_org_name', 'pods', ['organization_id', 'name'], unique=True, postgresql_where=sa.text('is_deleted IS false'))
    op.create_table('accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('auth_config_id', sa.Uuid(), nullable=False),
    sa.Column('connector_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allowed_scopes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auth_config_id'], ['auth_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_provider_account_id'), 'accounts', ['provider_account_id'], unique=False)
    op.create_index('ix_unique_user_auth_config_account', 'accounts', ['user_id', 'auth_config_id'], unique=True)
    op.create_table('agent_runtime_profiles',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('daemon_id', sa.Uuid(), nullable=True),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_model_name', sa.String(length=255), nullable=True),
    sa.Column('model_catalog', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('profile_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['daemon_id'], ['agent_runtime_daemons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runtime_profile_org_scope_status', 'agent_runtime_profiles', ['organization_id', 'scope', 'status'], unique=False)
    op.create_index('ix_agent_runtime_profile_org_status', 'agent_runtime_profiles', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_agent_runtime_profiles_daemon_id'), 'agent_runtime_profiles', ['daemon_id'], unique=False)
    op.create_index(op.f('ix_agent_runtime_profiles_id'), 'agent_runtime_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_agent_runtime_profiles_organization_id'), 'agent_runtime_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agent_runtime_profiles_scope'), 'agent_runtime_profiles', ['scope'], unique=False)
    op.create_index(op.f('ix_agent_runtime_profiles_status'), 'agent_runtime_profiles', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runtime_profiles_user_id'), 'agent_runtime_profiles', ['user_id'], unique=False)
    op.create_index('uq_agent_runtime_profile_org_name', 'agent_runtime_profiles', ['organization_id', 'name'], unique=True, postgresql_where=sa.text("scope = 'ORGANIZATION'"))
    op.create_index('uq_agent_runtime_profile_personal_name', 'agent_runtime_profiles', ['organization_id', 'user_id', 'name'], unique=True, postgresql_where=sa.text("scope = 'PERSONAL'"))
    op.create_table('agents',
    sa.Column('pod_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('agent_runtime', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('toolsets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pod_id', 'name', name='uq_agent_pod_name')
    )
    op.create_index('ix_agent_pod_name', 'agents', ['pod_id', 'name'], unique=False)
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=False)
    op.create_index(op.f('ix_agents_pod_id'), 'agents', ['pod_id'], unique=False)
    op.create_index(op.f('ix_agents_user_id'), 'agents', ['user_id'], unique=False)
    op.create_table('apps',
    sa.Column('pod_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('public_slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_archive_path', sa.String(), nullable=True),
    sa.Column('current_release_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pod_id', 'name', name='uq_app_pod_name'),
    sa.UniqueConstraint('public_slug', name='uq_app_public_slug')
    )
    op.create_index('ix_app_name', 'apps', ['name'], unique=False)
    op.create_index('ix_app_pod_name', 'apps', ['pod_id', 'name'], unique=False)
    op.create_index('ix_app_public_slug', 'apps', ['public_slug'], unique=False)
    op.create_index(op.f('ix_apps_id'), 'apps', ['id'], unique=False)
    op.create_table('connect_requests',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('auth_config_id', sa.Uuid(), nullable=False),
    sa.Column('connector_id', sa.String(length=255), nullable=False),
    sa.Column('authorization_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auth_config_id'], ['auth_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connect_requests_id'), 'connect_requests', ['id'], unique=False)
    op.create_table('datastore_files',
    sa.Column('pod_id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('search_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('file_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_processing_error', sa.Text(), nullable=True),
    sa.Column('processing_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_datastore_file_pod_path', 'datastore_files', ['pod_id', 'path'], unique=True)
    op.create_index('ix_datastore_file_pod_path_prefix', 'datastore_files', ['pod_id', 'path'], unique=False, postgresql_ops={'path': 'text_pattern_ops'})
    op.create_index('ix_datastore_file_status', 'datastore_files', ['pod_id', 'status'], unique=False)
    op.create_index(op.f('ix_datastore_files_id'), 'datastore_files', ['id'], unique=False)
    op.create_index(op.f('ix_datastore_files_owner_user_id'), 'datastore_files', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_datastore_files_pod_id'), 'datastore_files', ['pod_id'], unique=False)
    op.create_table('datastore_tables',
    sa.Column('pod_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('primary_key_column', sa.String(length=255), nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enable_rls', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_datastore_table_pod_name', 'datastore_tables', ['pod_id', 'table_name'], unique=True)
    op.create_index(op.f('ix_datastore_tables_id'), 'datastore_tables', ['id'], unique=False)
    op.create_index(op.f('ix_datastore_tables_pod_id'), 'datastore_tables', ['pod_id'], unique=False)
    op.create_table('functions',
    sa.Column('pod_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('code_path', sa.String(), nullable=True),
    sa.Column('code_hash', sa.String(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('python_packages', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pod_id', 'name', name='uq_function_pod_name')
    )
    op.create_index('ix_function_name', 'functions', ['name'], unique=False)
    op.create_index('ix_function_pod_name', 'functions', ['pod_id', 'name'], unique=False)
    op.create_index(op.f('ix_functions_id'), 'functions', ['id'], unique=False)
    op.create_table('organization_invitations',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('pod_id', sa.Uuid(), nullable=True),
    sa.Column('pod_role', sa.String(length=50), nullable=True),
    sa.Column('redirect_uri', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_org_invitation_email_org', 'organization_invitations', ['email', 'organization_id'], unique=True)
    op.create_index(op.f('ix_organization_invitations_email'), 'organization_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_organization_invitations_id'), 'organization_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_organization_invitations_status'), 'organization_invitations', ['status'], unique=False)
    op.create_table('pod_join_requests',
    sa.Column('pod_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('org_role', sa.String(length=50), nullable=True),
    sa.Column('pod_role', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pod_join_request_org_status', 'pod_join_requests', ['organization_id', 'status'], unique=False)
    op.create_index('ix_pod_join_request_pod_user_status', 'pod_join_requests', ['pod_id', 'user_id', 'status'], unique=False)
    op.create_index(op.f('ix_pod_join_requests_approved_by_user_id'), 'pod_join_requests', ['approved_by_user_id'], unique=False)
    op.create_index(op.f('ix_pod_join_requests_id'), 'pod_join_requests', ['id'], unique=False)
    op.create_index(op.f('ix_pod_join_requests_organization_id'), 'pod_join_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pod_join_requests_pod_id'), 'pod_join_requests', ['pod_id'], unique=False)
    op.create_index(op.f('ix_pod_join_requests_status'), 'pod_join_requests', ['status'], unique=False)
    op.create_index(op.f('ix_pod_join_requests_user_id'), 'pod_join_requests', ['user_id'], unique=False)
    op.create_table('pod_members',
    sa.Column('pod_id', sa.Uuid(), nullable=False),
    sa.Column('organization_member_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_member_id'], ['organization_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pod_member_pod_org_member', 'pod_members', ['pod_id', 'organization_member_id'], unique=True)
    op.create_index(op.f('ix_pod_members_id'), 'pod_members', ['id'], unique=False)
    op.create_table('resource_permission_grants',
    sa.Column('pod_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('grantee_type', sa.String(length=40), nullable=False),
    sa.Column('grantee_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pod_id', 'resource_type', 'resource_id', 'grantee_type', 'grantee_id', 'permission_id', name='uq_resource_permission_grants_scope')
    )
    op.create_index('ix_resource_permission_grants_grantee', 'resource_permission_grants', ['pod_id', 'grantee_type', 'grantee_id', 'permission_id'], unique=False)
    op.create_index(op.f('ix_resource_permission_grants_id'), 'resource_permission_grants', ['id'], unique=False)
    op.create_index('ix_resource_permission_grants_resource', 'resource_permission_grants', ['pod_id', 'resource_type', 'resource_id'], unique=False)
    op.create_index('ix_rpg_grantee_resource_permission', 'resource_permission_grants', ['pod_id', 'grantee_type', 'grantee_id', 'resource_type', 'permission_id', 'resource_id'], unique=False)
    op.create_index('ix_rpg_resource_permission_grantee', 'resource_permission_grants', ['pod_id', 'resource_type', 'resource_id', 'permission_id', 'grantee_type', 'grantee_id'], unique=False)
    op.create_table('roles',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('pod_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index('ix_roles_org_pod', 'roles', ['organization_id', 'pod_id'], unique=False)
    op.create_index('uq_roles_org_name', 'roles', ['organization_id', 'name'], unique=True, postgresql_where=sa.text('pod_id IS NULL'))
    op.create_index('uq_roles_pod_name', 'roles', ['pod_id', 'name'], unique=True, postgresql_where=sa.text('pod_id IS NOT NULL'))
    op.create_table('workflow_flows',
    sa.Column('pod_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('edges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entry_node_id', sa.String(), nullable=True),
    sa.Column('start', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pod_id', 'name', name='uq_workflow_flow_pod_name')
    )
    op.create_index('ix_workflow_flow_pod_name', 'workflow_flows', ['pod_id', 'name'], unique=False)
    op.create_index(op.f('ix_workflow_flows_id'), 'workflow_flows', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_flows_pod_id'), 'workflow_flows', ['pod_id'], unique=False)
    op.create_table('agent_conversations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pod_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('agent_runtime', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conversation_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['agent_conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_conv_metadata', 'agent_conversations', ['conversation_metadata'], unique=False, postgresql_using='gin')
    op.create_index('ix_agent_conv_parent', 'agent_conversations', ['parent_id'], unique=False)
    op.create_index('ix_agent_conv_pod_agent_roots', 'agent_conversations', ['pod_id', 'agent_id', 'user_id', 'parent_id', 'id'], unique=False)
    op.create_index('ix_agent_conv_pod_assistant_roots', 'agent_conversations', ['user_id', 'agent_id', 'pod_id', 'parent_id', 'id'], unique=False)
    op.create_index(op.f('ix_agent_conversations_agent_id'), 'agent_conversations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_conversations_conversation_type'), 'agent_conversations', ['conversation_type'], unique=False)
    op.create_index(op.f('ix_agent_conversations_id'), 'agent_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_agent_conversations_organization_id'), 'agent_conversations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agent_conversations_parent_id'), 'agent_conversations', ['parent_id'], unique=False)
    op.create_index(op.f('ix_agent_conversations_pod_id'), 'agent_conversations', ['pod_id'], unique=False)
    op.create_index(op.f('ix_agent_conversations_status'), 'agent_conversations', ['status'], unique=False)
    op.create_index(op.f('ix_agent_conversations_user_id'), 'agent_conversations', ['user_id'], unique=False)
    op.create_table('agent_feedback',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('issue_encountered', sa.Text(), nullable=False),
    sa.Column('expected_behavior', sa.Text(), nullable=False),
    sa.Column('actual_behavior', sa.Text(), nullable=False),
    sa.Column('suggested_next_steps', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_feedback_agent_created', 'agent_feedback', ['agent_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_feedback_agent_id'), 'agent_feedback', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_feedback_category'), 'agent_feedback', ['category'], unique=False)
    op.create_index(op.f('ix_agent_feedback_id'), 'agent_feedback', ['id'], unique=False)
    op.create_index('ix_agent_feedback_user_created', 'agent_feedback', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_feedback_user_id'), 'agent_feedback', ['user_id'], unique=False)
    op.create_table('app_releases',
    sa.Column('app_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('dist_root_path', sa.String(), nullable=False),
    sa.Column('dist_archive_path', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'version', name='uq_app_release_version')
    )
    op.create_index('ix_app_release_app_id', 'app_releases', ['app_id'], unique=False)
    op.create_index(op.f('ix_app_releases_id'), 'app_releases', ['id'], unique=False)
    op.create_table('function_runs',
    sa.Column('function_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('user_email', sa.Text(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('workspace_session_id', sa.String(), nullable=True),
    sa.Column('workspace_process_id', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_function_runs_id'), 'function_runs', ['id'], unique=False)
    op.create_table('role_assignments',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('principal_type', sa.String(length=40), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'principal_type', 'principal_id', name='uq_role_assignments_role_principal')
    )
    op.create_index(op.f('ix_role_assignments_id'), 'role_assignments', ['id'], unique=False)
    op.create_index('ix_role_assignments_principal', 'role_assignments', ['principal_type', 'principal_id'], unique=False)
    op.create_index('ix_role_assignments_role_id', 'role_assignments', ['role_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.String(), nullable=False),
    sa.Column('granted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_index('ix_role_permissions_permission', 'role_permissions', ['permission_id'], unique=False)
    op.create_table('schedules',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pod_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('schedule_type', sa.Enum('TIME', 'WEBHOOK', 'DATASTORE', name='scheduletype', native_enum=False, length=50), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('connector_trigger_id', sa.String(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filter_instruction', sa.Text(), nullable=True),
    sa.Column('filter_output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_id', sa.String(length=255), nullable=True),
    sa.Column('last_fire_status', sa.Enum('TRIGGERED', 'FILTERED', 'ERROR', name='schedulefirestatus', native_enum=False, length=20), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connector_trigger_id'], ['connector_triggers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schedules_account', 'schedules', ['account_id'], unique=False)
    op.create_index(op.f('ix_schedules_account_id'), 'schedules', ['account_id'], unique=False)
    op.create_index('ix_schedules_agent', 'schedules', ['agent_id'], unique=False)
    op.create_index(op.f('ix_schedules_agent_id'), 'schedules', ['agent_id'], unique=False)
    op.create_index('ix_schedules_config_gin', 'schedules', ['config'], unique=False, postgresql_using='gin')
    op.create_index('ix_schedules_connector_trigger', 'schedules', ['connector_trigger_id'], unique=False)
    op.create_index(op.f('ix_schedules_connector_trigger_id'), 'schedules', ['connector_trigger_id'], unique=False)
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_index(op.f('ix_schedules_is_active'), 'schedules', ['is_active'], unique=False)
    op.create_index(op.f('ix_schedules_is_internal'), 'schedules', ['is_internal'], unique=False)
    op.create_index(op.f('ix_schedules_name'), 'schedules', ['name'], unique=False)
    op.create_index(op.f('ix_schedules_pod_id'), 'schedules', ['pod_id'], unique=False)
    op.create_index(op.f('ix_schedules_schedule_type'), 'schedules', ['schedule_type'], unique=False)
    op.create_index('ix_schedules_type_active', 'schedules', ['schedule_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_schedules_user_id'), 'schedules', ['user_id'], unique=False)
    op.create_index('ix_schedules_user_pod', 'schedules', ['user_id', 'pod_id'], unique=False)
    op.create_index('ix_schedules_workflow', 'schedules', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_schedules_workflow_id'), 'schedules', ['workflow_id'], unique=False)
    op.create_index('uq_schedules_pod_name', 'schedules', ['pod_id', 'name'], unique=True, postgresql_where=sa.text('pod_id IS NOT NULL AND name IS NOT NULL AND is_internal = false'))
    op.create_table('workflow_flow_runs',
    sa.Column('flow_id', sa.Uuid(), nullable=False),
    sa.Column('pod_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('start_type', sa.String(), nullable=False),
    sa.Column('schedule_event_id', sa.String(), nullable=True),
    sa.Column('start_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_node_id', sa.String(), nullable=True),
    sa.Column('execution_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('execution_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('step_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('failed_node_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['workflow_flows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flow_id', 'user_id', 'schedule_event_id', name='uq_workflow_run_flow_user_schedule_event')
    )
    op.create_index(op.f('ix_workflow_flow_runs_flow_id'), 'workflow_flow_runs', ['flow_id'], unique=False)
    op.create_index(op.f('ix_workflow_flow_runs_id'), 'workflow_flow_runs', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_flow_runs_pod_id'), 'workflow_flow_runs', ['pod_id'], unique=False)
    op.create_index(op.f('ix_workflow_flow_runs_schedule_event_id'), 'workflow_flow_runs', ['schedule_event_id'], unique=False)
    op.create_index(op.f('ix_workflow_flow_runs_user_id'), 'workflow_flow_runs', ['user_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('parent_run_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('agent_runtime', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('run_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_run_conversation_created', 'agent_runs', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_agent_run_conversation_status', 'agent_runs', ['conversation_id', 'status'], unique=False)
    op.create_index(op.f('ix_agent_runs_agent_id'), 'agent_runs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_conversation_id'), 'agent_runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_id'), 'agent_runs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_runs_parent_run_id'), 'agent_runs', ['parent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index('uq_agent_active_run_per_conversation', 'agent_runs', ['conversation_id'], unique=True, postgresql_where=sa.text("status IN ('RUNNING', 'STOP_REQUESTED', 'running', 'stop_requested')"))
    op.create_table('agent_surfaces',
    sa.Column('pod_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('surface_type', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.String(length=50), server_default='DM', nullable=False),
    sa.Column('event_mode', sa.String(length=50), server_default='WEBHOOK', nullable=False),
    sa.Column('credential_mode', sa.String(length=50), server_default='SYSTEM', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('external_workspace_id', sa.String(length=255), nullable=True),
    sa.Column('external_tenant_id', sa.String(length=255), nullable=True),
    sa.Column('external_channel_id', sa.String(length=255), nullable=True),
    sa.Column('surface_identity_id', sa.String(length=255), nullable=True),
    sa.Column('surface_identity_username', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='ACTIVE', nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=True),
    sa.Column('surface_identity_email', sa.String(length=255), nullable=True),
    sa.Column('webhook_secret', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_surfaces_account_id'), 'agent_surfaces', ['account_id'], unique=False)
    op.create_index(op.f('ix_agent_surfaces_agent_id'), 'agent_surfaces', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_surfaces_credential_mode'), 'agent_surfaces', ['credential_mode'], unique=False)
    op.create_index(op.f('ix_agent_surfaces_event_mode'), 'agent_surfaces', ['event_mode'], unique=False)
    op.create_index(op.f('ix_agent_surfaces_external_channel_id'), 'agent_surfaces', ['external_channel_id'], unique=False)
    op.create_index(op.f('ix_agent_surfaces_external_tenant_id'), 'agent_surfaces', ['external_tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_surfaces_external_workspace_id'), 'agent_surfaces', ['external_workspace_id'], unique=False)
    op.create_index(op.f('ix_agent_surfaces_id'), 'agent_surfaces', ['id'], unique=False)
    op.create_index(op.f('ix_agent_surfaces_mode'), 'agent_surfaces', ['mode'], unique=False)
    op.create_index(op.f('ix_agent_surfaces_pod_id'), 'agent_surfaces', ['pod_id'], unique=False)
    op.create_index(op.f('ix_agent_surfaces_schedule_id'), 'agent_surfaces', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_agent_surfaces_surface_identity_email'), 'agent_surfaces', ['surface_identity_email'], unique=False)
    op.create_index(op.f('ix_agent_surfaces_surface_identity_id'), 'agent_surfaces', ['surface_identity_id'], unique=False)
    op.create_index(op.f('ix_agent_surfaces_surface_identity_username'), 'agent_surfaces', ['surface_identity_username'], unique=False)
    op.create_index(op.f('ix_agent_surfaces_surface_type'), 'agent_surfaces', ['surface_type'], unique=False)
    op.create_table('workflow_run_waits',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('flow_id', sa.Uuid(), nullable=False),
    sa.Column('pod_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('wait_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_pod_member_id', sa.Uuid(), nullable=True),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_pod_member_id'], ['pod_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['flow_id'], ['workflow_flows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_flow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_run_waits_assigned_pod_member_id'), 'workflow_run_waits', ['assigned_pod_member_id'], unique=False)
    op.create_index('ix_workflow_run_waits_assignee_status', 'workflow_run_waits', ['assigned_pod_member_id', 'status'], unique=False)
    op.create_index('ix_workflow_run_waits_external_ref', 'workflow_run_waits', ['external_ref'], unique=False)
    op.create_index(op.f('ix_workflow_run_waits_flow_id'), 'workflow_run_waits', ['flow_id'], unique=False)
    op.create_index(op.f('ix_workflow_run_waits_id'), 'workflow_run_waits', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_run_waits_pod_id'), 'workflow_run_waits', ['pod_id'], unique=False)
    op.create_index(op.f('ix_workflow_run_waits_run_id'), 'workflow_run_waits', ['run_id'], unique=False)
    op.create_index('ix_workflow_run_waits_run_status', 'workflow_run_waits', ['run_id', 'status'], unique=False)
    op.create_index(op.f('ix_workflow_run_waits_status'), 'workflow_run_waits', ['status'], unique=False)
    op.create_index('ix_workflow_run_waits_type_ref_status', 'workflow_run_waits', ['wait_type', 'external_ref', 'status'], unique=False)
    op.create_index(op.f('ix_workflow_run_waits_wait_type'), 'workflow_run_waits', ['wait_type'], unique=False)
    op.create_index('uq_workflow_run_waits_one_active', 'workflow_run_waits', ['run_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('agent_approval_decisions',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('approval_id', sa.String(length=255), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'approval_id', name='uq_agent_approval_decision')
    )
    op.create_index('ix_agent_approval_decision_conversation', 'agent_approval_decisions', ['conversation_id', 'approval_id'], unique=False)
    op.create_index(op.f('ix_agent_approval_decisions_conversation_id'), 'agent_approval_decisions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_approval_decisions_id'), 'agent_approval_decisions', ['id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('tool_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_call_id', sa.String(length=255), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=True),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'sequence', name='uq_agent_message_sequence')
    )
    op.create_index('ix_agent_message_conversation_sequence', 'agent_messages', ['conversation_id', 'sequence'], unique=False)
    op.create_index('ix_agent_message_run_sequence', 'agent_messages', ['agent_run_id', 'sequence'], unique=False)
    op.create_index('ix_agent_message_tool_call', 'agent_messages', ['tool_call_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_agent_run_id'), 'agent_messages', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_conversation_id'), 'agent_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_id'), 'agent_messages', ['id'], unique=False)
    op.create_index(op.f('ix_agent_messages_role'), 'agent_messages', ['role'], unique=False)
    op.create_table('agent_surface_conversation_links',
    sa.Column('surface_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('external_channel_id', sa.String(length=255), nullable=True),
    sa.Column('external_thread_id', sa.String(length=255), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=True),
    sa.Column('routed_agent_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_kind', sa.String(length=50), server_default='DM', nullable=False),
    sa.Column('route_key', sa.String(length=255), nullable=True),
    sa.Column('last_event', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_message_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['routed_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['surface_id'], ['agent_surfaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_surface_conversation_links_conversation_id'), 'agent_surface_conversation_links', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_surface_conversation_links_id'), 'agent_surface_conversation_links', ['id'], unique=False)
    op.create_index(op.f('ix_agent_surface_conversation_links_platform'), 'agent_surface_conversation_links', ['platform'], unique=False)
    op.create_index(op.f('ix_agent_surface_conversation_links_route_key'), 'agent_surface_conversation_links', ['route_key'], unique=False)
    op.create_index(op.f('ix_agent_surface_conversation_links_routed_agent_id'), 'agent_surface_conversation_links', ['routed_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_surface_conversation_links_surface_id'), 'agent_surface_conversation_links', ['surface_id'], unique=False)
    op.create_index('ix_agent_surface_link_conversation', 'agent_surface_conversation_links', ['conversation_id'], unique=False)
    op.create_index('ix_agent_surface_link_external_thread', 'agent_surface_conversation_links', ['surface_id', 'platform', 'external_channel_id', 'external_thread_id', 'external_user_id'], unique=True)
    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_surface_link_external_thread', table_name='agent_surface_conversation_links')
    op.drop_index('ix_agent_surface_link_conversation', table_name='agent_surface_conversation_links')
    op.drop_index(op.f('ix_agent_surface_conversation_links_surface_id'), table_name='agent_surface_conversation_links')
    op.drop_index(op.f('ix_agent_surface_conversation_links_routed_agent_id'), table_name='agent_surface_conversation_links')
    op.drop_index(op.f('ix_agent_surface_conversation_links_route_key'), table_name='agent_surface_conversation_links')
    op.drop_index(op.f('ix_agent_surface_conversation_links_platform'), table_name='agent_surface_conversation_links')
    op.drop_index(op.f('ix_agent_surface_conversation_links_id'), table_name='agent_surface_conversation_links')
    op.drop_index(op.f('ix_agent_surface_conversation_links_conversation_id'), table_name='agent_surface_conversation_links')
    op.drop_table('agent_surface_conversation_links')
    op.drop_index(op.f('ix_agent_messages_role'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_conversation_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_agent_run_id'), table_name='agent_messages')
    op.drop_index('ix_agent_message_tool_call', table_name='agent_messages')
    op.drop_index('ix_agent_message_run_sequence', table_name='agent_messages')
    op.drop_index('ix_agent_message_conversation_sequence', table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_agent_approval_decisions_id'), table_name='agent_approval_decisions')
    op.drop_index(op.f('ix_agent_approval_decisions_conversation_id'), table_name='agent_approval_decisions')
    op.drop_index('ix_agent_approval_decision_conversation', table_name='agent_approval_decisions')
    op.drop_table('agent_approval_decisions')
    op.drop_index('uq_workflow_run_waits_one_active', table_name='workflow_run_waits', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_workflow_run_waits_wait_type'), table_name='workflow_run_waits')
    op.drop_index('ix_workflow_run_waits_type_ref_status', table_name='workflow_run_waits')
    op.drop_index(op.f('ix_workflow_run_waits_status'), table_name='workflow_run_waits')
    op.drop_index('ix_workflow_run_waits_run_status', table_name='workflow_run_waits')
    op.drop_index(op.f('ix_workflow_run_waits_run_id'), table_name='workflow_run_waits')
    op.drop_index(op.f('ix_workflow_run_waits_pod_id'), table_name='workflow_run_waits')
    op.drop_index(op.f('ix_workflow_run_waits_id'), table_name='workflow_run_waits')
    op.drop_index(op.f('ix_workflow_run_waits_flow_id'), table_name='workflow_run_waits')
    op.drop_index('ix_workflow_run_waits_external_ref', table_name='workflow_run_waits')
    op.drop_index('ix_workflow_run_waits_assignee_status', table_name='workflow_run_waits')
    op.drop_index(op.f('ix_workflow_run_waits_assigned_pod_member_id'), table_name='workflow_run_waits')
    op.drop_table('workflow_run_waits')
    op.drop_index(op.f('ix_agent_surfaces_surface_type'), table_name='agent_surfaces')
    op.drop_index(op.f('ix_agent_surfaces_surface_identity_username'), table_name='agent_surfaces')
    op.drop_index(op.f('ix_agent_surfaces_surface_identity_id'), table_name='agent_surfaces')
    op.drop_index(op.f('ix_agent_surfaces_surface_identity_email'), table_name='agent_surfaces')
    op.drop_index(op.f('ix_agent_surfaces_schedule_id'), table_name='agent_surfaces')
    op.drop_index(op.f('ix_agent_surfaces_pod_id'), table_name='agent_surfaces')
    op.drop_index(op.f('ix_agent_surfaces_mode'), table_name='agent_surfaces')
    op.drop_index(op.f('ix_agent_surfaces_id'), table_name='agent_surfaces')
    op.drop_index(op.f('ix_agent_surfaces_external_workspace_id'), table_name='agent_surfaces')
    op.drop_index(op.f('ix_agent_surfaces_external_tenant_id'), table_name='agent_surfaces')
    op.drop_index(op.f('ix_agent_surfaces_external_channel_id'), table_name='agent_surfaces')
    op.drop_index(op.f('ix_agent_surfaces_event_mode'), table_name='agent_surfaces')
    op.drop_index(op.f('ix_agent_surfaces_credential_mode'), table_name='agent_surfaces')
    op.drop_index(op.f('ix_agent_surfaces_agent_id'), table_name='agent_surfaces')
    op.drop_index(op.f('ix_agent_surfaces_account_id'), table_name='agent_surfaces')
    op.drop_table('agent_surfaces')
    op.drop_index('uq_agent_active_run_per_conversation', table_name='agent_runs', postgresql_where=sa.text("status IN ('RUNNING', 'STOP_REQUESTED', 'running', 'stop_requested')"))
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_parent_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_conversation_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_id'), table_name='agent_runs')
    op.drop_index('ix_agent_run_conversation_status', table_name='agent_runs')
    op.drop_index('ix_agent_run_conversation_created', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_workflow_flow_runs_user_id'), table_name='workflow_flow_runs')
    op.drop_index(op.f('ix_workflow_flow_runs_schedule_event_id'), table_name='workflow_flow_runs')
    op.drop_index(op.f('ix_workflow_flow_runs_pod_id'), table_name='workflow_flow_runs')
    op.drop_index(op.f('ix_workflow_flow_runs_id'), table_name='workflow_flow_runs')
    op.drop_index(op.f('ix_workflow_flow_runs_flow_id'), table_name='workflow_flow_runs')
    op.drop_table('workflow_flow_runs')
    op.drop_index('uq_schedules_pod_name', table_name='schedules', postgresql_where=sa.text('pod_id IS NOT NULL AND name IS NOT NULL AND is_internal = false'))
    op.drop_index(op.f('ix_schedules_workflow_id'), table_name='schedules')
    op.drop_index('ix_schedules_workflow', table_name='schedules')
    op.drop_index('ix_schedules_user_pod', table_name='schedules')
    op.drop_index(op.f('ix_schedules_user_id'), table_name='schedules')
    op.drop_index('ix_schedules_type_active', table_name='schedules')
    op.drop_index(op.f('ix_schedules_schedule_type'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_pod_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_name'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_is_internal'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_is_active'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_connector_trigger_id'), table_name='schedules')
    op.drop_index('ix_schedules_connector_trigger', table_name='schedules')
    op.drop_index('ix_schedules_config_gin', table_name='schedules', postgresql_using='gin')
    op.drop_index(op.f('ix_schedules_agent_id'), table_name='schedules')
    op.drop_index('ix_schedules_agent', table_name='schedules')
    op.drop_index(op.f('ix_schedules_account_id'), table_name='schedules')
    op.drop_index('ix_schedules_account', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index('ix_role_permissions_permission', table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_role_assignments_role_id', table_name='role_assignments')
    op.drop_index('ix_role_assignments_principal', table_name='role_assignments')
    op.drop_index(op.f('ix_role_assignments_id'), table_name='role_assignments')
    op.drop_table('role_assignments')
    op.drop_index(op.f('ix_function_runs_id'), table_name='function_runs')
    op.drop_table('function_runs')
    op.drop_index(op.f('ix_app_releases_id'), table_name='app_releases')
    op.drop_index('ix_app_release_app_id', table_name='app_releases')
    op.drop_table('app_releases')
    op.drop_index(op.f('ix_agent_feedback_user_id'), table_name='agent_feedback')
    op.drop_index('ix_agent_feedback_user_created', table_name='agent_feedback')
    op.drop_index(op.f('ix_agent_feedback_id'), table_name='agent_feedback')
    op.drop_index(op.f('ix_agent_feedback_category'), table_name='agent_feedback')
    op.drop_index(op.f('ix_agent_feedback_agent_id'), table_name='agent_feedback')
    op.drop_index('ix_agent_feedback_agent_created', table_name='agent_feedback')
    op.drop_table('agent_feedback')
    op.drop_index(op.f('ix_agent_conversations_user_id'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_status'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_pod_id'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_parent_id'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_organization_id'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_id'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_conversation_type'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_agent_id'), table_name='agent_conversations')
    op.drop_index('ix_agent_conv_pod_assistant_roots', table_name='agent_conversations')
    op.drop_index('ix_agent_conv_pod_agent_roots', table_name='agent_conversations')
    op.drop_index('ix_agent_conv_parent', table_name='agent_conversations')
    op.drop_index('ix_agent_conv_metadata', table_name='agent_conversations', postgresql_using='gin')
    op.drop_table('agent_conversations')
    op.drop_index(op.f('ix_workflow_flows_pod_id'), table_name='workflow_flows')
    op.drop_index(op.f('ix_workflow_flows_id'), table_name='workflow_flows')
    op.drop_index('ix_workflow_flow_pod_name', table_name='workflow_flows')
    op.drop_table('workflow_flows')
    op.drop_index('uq_roles_pod_name', table_name='roles', postgresql_where=sa.text('pod_id IS NOT NULL'))
    op.drop_index('uq_roles_org_name', table_name='roles', postgresql_where=sa.text('pod_id IS NULL'))
    op.drop_index('ix_roles_org_pod', table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_rpg_resource_permission_grantee', table_name='resource_permission_grants')
    op.drop_index('ix_rpg_grantee_resource_permission', table_name='resource_permission_grants')
    op.drop_index('ix_resource_permission_grants_resource', table_name='resource_permission_grants')
    op.drop_index(op.f('ix_resource_permission_grants_id'), table_name='resource_permission_grants')
    op.drop_index('ix_resource_permission_grants_grantee', table_name='resource_permission_grants')
    op.drop_table('resource_permission_grants')
    op.drop_index(op.f('ix_pod_members_id'), table_name='pod_members')
    op.drop_index('ix_pod_member_pod_org_member', table_name='pod_members')
    op.drop_table('pod_members')
    op.drop_index(op.f('ix_pod_join_requests_user_id'), table_name='pod_join_requests')
    op.drop_index(op.f('ix_pod_join_requests_status'), table_name='pod_join_requests')
    op.drop_index(op.f('ix_pod_join_requests_pod_id'), table_name='pod_join_requests')
    op.drop_index(op.f('ix_pod_join_requests_organization_id'), table_name='pod_join_requests')
    op.drop_index(op.f('ix_pod_join_requests_id'), table_name='pod_join_requests')
    op.drop_index(op.f('ix_pod_join_requests_approved_by_user_id'), table_name='pod_join_requests')
    op.drop_index('ix_pod_join_request_pod_user_status', table_name='pod_join_requests')
    op.drop_index('ix_pod_join_request_org_status', table_name='pod_join_requests')
    op.drop_table('pod_join_requests')
    op.drop_index(op.f('ix_organization_invitations_status'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_id'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_email'), table_name='organization_invitations')
    op.drop_index('ix_org_invitation_email_org', table_name='organization_invitations')
    op.drop_table('organization_invitations')
    op.drop_index(op.f('ix_functions_id'), table_name='functions')
    op.drop_index('ix_function_pod_name', table_name='functions')
    op.drop_index('ix_function_name', table_name='functions')
    op.drop_table('functions')
    op.drop_index(op.f('ix_datastore_tables_pod_id'), table_name='datastore_tables')
    op.drop_index(op.f('ix_datastore_tables_id'), table_name='datastore_tables')
    op.drop_index('ix_datastore_table_pod_name', table_name='datastore_tables')
    op.drop_table('datastore_tables')
    op.drop_index(op.f('ix_datastore_files_pod_id'), table_name='datastore_files')
    op.drop_index(op.f('ix_datastore_files_owner_user_id'), table_name='datastore_files')
    op.drop_index(op.f('ix_datastore_files_id'), table_name='datastore_files')
    op.drop_index('ix_datastore_file_status', table_name='datastore_files')
    op.drop_index('ix_datastore_file_pod_path_prefix', table_name='datastore_files', postgresql_ops={'path': 'text_pattern_ops'})
    op.drop_index('ix_datastore_file_pod_path', table_name='datastore_files')
    op.drop_table('datastore_files')
    op.drop_index(op.f('ix_connect_requests_id'), table_name='connect_requests')
    op.drop_table('connect_requests')
    op.drop_index(op.f('ix_apps_id'), table_name='apps')
    op.drop_index('ix_app_public_slug', table_name='apps')
    op.drop_index('ix_app_pod_name', table_name='apps')
    op.drop_index('ix_app_name', table_name='apps')
    op.drop_table('apps')
    op.drop_index(op.f('ix_agents_user_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_pod_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_index('ix_agent_pod_name', table_name='agents')
    op.drop_table('agents')
    op.drop_index('uq_agent_runtime_profile_personal_name', table_name='agent_runtime_profiles', postgresql_where=sa.text("scope = 'PERSONAL'"))
    op.drop_index('uq_agent_runtime_profile_org_name', table_name='agent_runtime_profiles', postgresql_where=sa.text("scope = 'ORGANIZATION'"))
    op.drop_index(op.f('ix_agent_runtime_profiles_user_id'), table_name='agent_runtime_profiles')
    op.drop_index(op.f('ix_agent_runtime_profiles_status'), table_name='agent_runtime_profiles')
    op.drop_index(op.f('ix_agent_runtime_profiles_scope'), table_name='agent_runtime_profiles')
    op.drop_index(op.f('ix_agent_runtime_profiles_organization_id'), table_name='agent_runtime_profiles')
    op.drop_index(op.f('ix_agent_runtime_profiles_id'), table_name='agent_runtime_profiles')
    op.drop_index(op.f('ix_agent_runtime_profiles_daemon_id'), table_name='agent_runtime_profiles')
    op.drop_index('ix_agent_runtime_profile_org_status', table_name='agent_runtime_profiles')
    op.drop_index('ix_agent_runtime_profile_org_scope_status', table_name='agent_runtime_profiles')
    op.drop_table('agent_runtime_profiles')
    op.drop_index('ix_unique_user_auth_config_account', table_name='accounts')
    op.drop_index(op.f('ix_accounts_provider_account_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('uq_pod_active_org_name', table_name='pods', postgresql_where=sa.text('is_deleted IS false'))
    op.drop_index(op.f('ix_pods_user_id'), table_name='pods')
    op.drop_index(op.f('ix_pods_organization_id'), table_name='pods')
    op.drop_index(op.f('ix_pods_name'), table_name='pods')
    op.drop_index(op.f('ix_pods_is_deleted'), table_name='pods')
    op.drop_index(op.f('ix_pods_id'), table_name='pods')
    op.drop_index('ix_pod_user_name', table_name='pods')
    op.drop_index('ix_pod_org_name', table_name='pods')
    op.drop_table('pods')
    op.drop_index(op.f('ix_organization_members_id'), table_name='organization_members')
    op.drop_index('ix_org_member_user_org', table_name='organization_members')
    op.drop_index('ix_org_member_org_role', table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_connector_triggers_id'), table_name='connector_triggers')
    op.drop_index('ix_connector_triggers_app_provider_event', table_name='connector_triggers')
    op.drop_table('connector_triggers')
    op.drop_index(op.f('ix_connector_operations_id'), table_name='connector_operations')
    op.drop_index('ix_connector_operations_app_provider_operation', table_name='connector_operations')
    op.drop_index('ix_connector_operations_app_provider_name', table_name='connector_operations')
    op.drop_table('connector_operations')
    op.drop_index('ix_auth_configs_unique_active_org_name', table_name='auth_configs', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('ix_auth_configs_unique_active_org_app', table_name='auth_configs', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('ix_auth_configs_org_status', table_name='auth_configs')
    op.drop_index(op.f('ix_auth_configs_id'), table_name='auth_configs')
    op.drop_index('ix_auth_configs_app_provider_status', table_name='auth_configs')
    op.drop_table('auth_configs')
    op.drop_index(op.f('ix_agent_surface_external_users_resolved_user_id'), table_name='agent_surface_external_users')
    op.drop_index(op.f('ix_agent_surface_external_users_platform'), table_name='agent_surface_external_users')
    op.drop_index(op.f('ix_agent_surface_external_users_phone'), table_name='agent_surface_external_users')
    op.drop_index(op.f('ix_agent_surface_external_users_id'), table_name='agent_surface_external_users')
    op.drop_index(op.f('ix_agent_surface_external_users_email'), table_name='agent_surface_external_users')
    op.drop_index('ix_agent_surface_external_user_platform_tenant_external', table_name='agent_surface_external_users')
    op.drop_table('agent_surface_external_users')
    op.drop_index('ix_agent_runtime_daemons_user_status', table_name='agent_runtime_daemons')
    op.drop_index(op.f('ix_agent_runtime_daemons_user_id'), table_name='agent_runtime_daemons')
    op.drop_index(op.f('ix_agent_runtime_daemons_status'), table_name='agent_runtime_daemons')
    op.drop_index(op.f('ix_agent_runtime_daemons_id'), table_name='agent_runtime_daemons')
    op.drop_table('agent_runtime_daemons')
    op.drop_index(op.f('ix_users_telegram_username'), table_name='users')
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_usage_user_time', table_name='usage_records')
    op.drop_index('ix_usage_source_time', table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_usage_kind'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_source_type'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_source_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_profile_scope'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_profile_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_pod_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_parent_agent_run_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_organization_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_occurred_at'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_model_name'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_conversation_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_agent_run_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_agent_id'), table_name='usage_records')
    op.drop_index('ix_usage_pod_time', table_name='usage_records')
    op.drop_index('ix_usage_org_user_profile_scope_time', table_name='usage_records')
    op.drop_index('ix_usage_org_time', table_name='usage_records')
    op.drop_index('ix_usage_org_profile_time', table_name='usage_records')
    op.drop_index('ix_usage_org_profile_scope_time', table_name='usage_records')
    op.drop_index('ix_usage_agent_time', table_name='usage_records')
    op.drop_index('ix_usage_agent_run_time', table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index('uq_usage_limit_counter_window', table_name='usage_limit_counters')
    op.drop_index(op.f('ix_usage_limit_counters_window_kind'), table_name='usage_limit_counters')
    op.drop_index(op.f('ix_usage_limit_counters_user_id'), table_name='usage_limit_counters')
    op.drop_index(op.f('ix_usage_limit_counters_organization_id'), table_name='usage_limit_counters')
    op.drop_index(op.f('ix_usage_limit_counters_id'), table_name='usage_limit_counters')
    op.drop_table('usage_limit_counters')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_email_domain'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_connectors_id'), table_name='connectors')
    op.drop_table('connectors')
    op.drop_index(op.f('ix_auth_permissions_id'), table_name='auth_permissions')
    op.drop_table('auth_permissions')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
