#!/usr/bin/env python3
"""Rewrite the generated ``openapi_client/models/__init__.py`` to import lazily.

openapi-python-client emits a ``models/__init__.py`` that eagerly imports every
generated model (450+ ``attrs`` classes). Because Python runs a package's
``__init__`` before resolving any submodule, a single
``from ...models.foo import Foo`` drags in *all* models — adding ~10s of import
time inside the agentbox runtime (no bytecode cache, constrained CPU).

This script replaces the eager imports with a PEP 562 ``__getattr__`` lazy
loader. Submodule imports (``from ...models.foo import Foo``) then only run the
cheap ``__init__`` plus ``foo``; package-level access
(``from ...models import Foo``) still works, resolved on first use. A
``TYPE_CHECKING`` block preserves the eager imports for type checkers and IDEs.

Idempotent: running on an already-lazy file is a no-op. Invoked automatically by
``generate_openapi_client.sh`` after generation; safe to run by hand too.
"""
from __future__ import annotations

import ast
import sys
from pathlib import Path

MARKER = "# LAZY-MODELS-INIT (generated by scripts/make_models_init_lazy.py)"


def parse_mapping(source: str) -> list[tuple[str, str]]:
    """Return (exported_name, submodule) pairs from eager `from .mod import X`."""
    tree = ast.parse(source)
    pairs: list[tuple[str, str]] = []
    for node in tree.body:
        if isinstance(node, ast.ImportFrom) and node.level == 1 and node.module:
            for alias in node.names:
                pairs.append((alias.asname or alias.name, node.module))
    return pairs


def render(pairs: list[tuple[str, str]]) -> str:
    pairs = sorted(set(pairs))
    name_to_mod = "\n".join(f"    {name!r}: {mod!r}," for name, mod in pairs)
    type_imports = "\n".join(
        f"    from .{mod} import {name}" for name, mod in pairs
    )
    all_names = "\n".join(f"    {name!r}," for name, _ in pairs)
    return f'''"""Contains all the data models used in inputs/outputs"""
{MARKER}
# Models are imported lazily: importing one model no longer drags in all 450+.
# Regenerate with scripts/generate_openapi_client.sh (this lazy form is
# reapplied automatically by scripts/make_models_init_lazy.py).
from __future__ import annotations

import importlib
from typing import TYPE_CHECKING

_NAME_TO_MODULE = {{
{name_to_mod}
}}

if TYPE_CHECKING:
{type_imports or "    pass"}


def __getattr__(name: str):
    module = _NAME_TO_MODULE.get(name)
    if module is None:
        raise AttributeError(f"module {{__name__!r}} has no attribute {{name!r}}")
    value = getattr(importlib.import_module(f".{{module}}", __name__), name)
    globals()[name] = value  # cache for subsequent lookups
    return value


def __dir__() -> list[str]:
    return sorted(_NAME_TO_MODULE)


__all__ = [
{all_names}
]
'''


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: make_models_init_lazy.py <openapi_client/models/__init__.py>", file=sys.stderr)
        return 2
    path = Path(sys.argv[1])
    source = path.read_text(encoding="utf-8")
    if MARKER in source:
        print(f"{path} already lazy; nothing to do")
        return 0
    pairs = parse_mapping(source)
    if not pairs:
        print(f"no eager imports found in {path}; leaving unchanged", file=sys.stderr)
        return 1
    path.write_text(render(pairs), encoding="utf-8")
    print(f"rewrote {path} -> lazy ({len(set(pairs))} models)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
