"""Contract: migrations/env.py imports every module that defines tables.

The Alembic baseline is autogenerated from ``Base.metadata``, which only
contains models that ``migrations/env.py`` has imported. A model module that
env.py forgets to import is silently dropped from the baseline — exactly how
``usage_records`` went missing. This test fails loudly if any model module
(``app/modules/<name>/infrastructure/models[.py]``) is not imported by env.py.
"""

from __future__ import annotations

from pathlib import Path

# app/modules/test_support/this_file.py -> lemma-backend/
_BACKEND_ROOT = Path(__file__).resolve().parents[3]
_MODULES_DIR = _BACKEND_ROOT / "app" / "modules"
_ENV_PY = _BACKEND_ROOT / "migrations" / "env.py"


def _model_modules() -> list[str]:
    """Module names whose infrastructure layer actually defines ORM tables.

    Keyed on a real ``__tablename__`` so an empty or stale ``models`` directory
    (e.g. a leftover from a rename) never counts as a model module.
    """
    names: list[str] = []
    for module in sorted(p for p in _MODULES_DIR.iterdir() if p.is_dir()):
        infra = module / "infrastructure"
        model_paths: list[Path] = []
        if (infra / "models.py").exists():
            model_paths.append(infra / "models.py")
        if (infra / "models").is_dir():
            model_paths.extend((infra / "models").rglob("*.py"))
        if any("__tablename__" in p.read_text(encoding="utf-8") for p in model_paths):
            names.append(module.name)
    return names


def test_env_py_imports_every_model_module() -> None:
    env_src = _ENV_PY.read_text(encoding="utf-8")
    missing = [
        name
        for name in _model_modules()
        if f"app.modules.{name}.infrastructure import models" not in env_src
        and f"app.modules.{name}.infrastructure.models" not in env_src
    ]
    assert not missing, (
        "migrations/env.py must import these model modules, or "
        "`alembic revision --autogenerate` drops their tables from the baseline: "
        f"{missing}"
    )
